Country National Society Projects Page
IFRCGo/go-web-app pull request #100
Opened 2023-08-25 08:19 UTC by samshara

## Changes
- Show national society project statistics
- Map view for the national society's projects
- List view of all the national society's ongoing projects

## This PR doesn't introduce:
- [x] typos
- [x] conflict markers
- [x] unwanted comments
- [x] temporary files, auto-generated files or secret keys
- [x] `console.log` meant for debugging
- [x] codegen errors

2023-08-25 08:21 UTC, samshara commented
Let's merge this after https://github.com/IFRCGo/go-web-app/pull/83. 
For testing http://localhost:3000/countries/14/three-w/ns-projects is a good example.

2023-08-28 16:12 UTC, tnagorra requested changes

2023-08-28 16:12 UTC, tnagorra commented on src/views/CountryThreeWNationalSocietyProjects/Map/index.tsx
> +            },
We cannot use default [0, 0] for coordinates

2023-08-28 16:12 UTC, tnagorra commented on src/views/CountryThreeWNationalSocietyProjects/Map/index.tsx
> +                    coordinates: country.centroid?.coordinates as [number, number] ?? [],
We cannot use default [] for coordinates

2023-08-28 16:12 UTC, tnagorra commented on src/views/CountryThreeWNationalSocietyProjects/Map/index.tsx
> +        [countries, projectList],
Let's just separate into different useMemo

2023-08-28 16:12 UTC, tnagorra commented on src/views/CountryThreeWNationalSocietyProjects/Map/index.tsx
> +                    {clickedPointProperties?.lngLat && clickedPointProperties.feature.id && (
Let's use isDefined

2023-08-28 16:21 UTC, merged