Update validation for number input in local unit form
IFRCGo/go-web-app pull request #1112
Opened 2024-05-27 09:22 UTC by shreeyash07

## Addresses:
- #1108 

## Changes
- update validation for number input in local unit form

## This PR doesn't introduce:
- [x] typos
- [x] conflict markers
- [x] unwanted comments
- [x] temporary files, auto-generated files or secret keys
- [x] `console.log` meant for debugging
- [x] codegen errors

2024-05-27 11:32 UTC, samshara requested changes

2024-05-27 11:32 UTC, samshara commented on app/src/views/CountryNsOverviewContextAndStructure/NationalSocietyLocalUnits/LocalUnitsFormModal/LocalUnitsForm/schema.ts
> +                                        greaterThanOrEqualToCondition(0),
We should add an `integerCondition` on fields that are supposed to be integers. It appears that the `maximum_capacity` field can currently accept floating point numbers, which is likely a mistake.

2024-05-27 11:32 UTC, samshara commented on app/src/views/CountryNsOverviewContextAndStructure/NationalSocietyLocalUnits/LocalUnitsFormModal/LocalUnitsForm/schema.ts
> +                                        greaterThanOrEqualToCondition(0),
Let's add similar validations for all fields.

2024-05-28 05:45 UTC, samshara requested changes

2024-05-28 05:45 UTC, samshara commented on app/src/views/CountryNsOverviewContextAndStructure/NationalSocietyLocalUnits/LocalUnitsFormModal/LocalUnitsForm/schema.ts
> +                                        greaterThanOrEqualToCondition(0),
we could use `positiveIntegerCondition` from `#utils/form`. Let's do this for all the following as well.

2024-05-29 02:28 UTC, frozenhelium approved these changes

2024-06-13 08:04 UTC, samshara approved these changes

2024-06-13 08:07 UTC, merged