Operational Learning excerpts export
IFRCGo/go-web-app pull request #1369
Opened 2024-09-13 09:03 UTC by puranban

## Addresses:
- https://github.com/IFRCGo/go-web-app/issues/1362
- https://github.com/IFRCGo/go-web-app/issues/1363
- https://github.com/IFRCGo/go-web-app/issues/1364

## Changes
- Add excerpts csv export in ops learning

## This PR doesn't introduce:
- [ ] typos
- [x] conflict markers
- [x] unwanted comments
- [x] temporary files, auto-generated files or secret keys
- [x] `console.log` meant for debugging
- [x] codegen errors

2024-10-08 08:19 UTC, samshara approved these changes

2024-10-08 10:22 UTC, tnagorra requested changes

2024-10-08 10:22 UTC, tnagorra commented on packages/ui/src/components/DismissableTextOutput/index.tsx
The name might not be correct.

2024-10-08 10:22 UTC, tnagorra commented on packages/ui/src/components/DismissableMultiListOutput/index.tsx
> +        }
This check can be simplified.

2024-10-08 10:22 UTC, tnagorra commented on packages/ui/src/components/DismissableListOutput/index.tsx
> +        }
This check can be simplified.

2024-10-08 10:22 UTC, tnagorra commented on app/src/views/RootLayout/index.tsx
> +                    break;
We need to make these consistent with the endpoint url

2024-10-08 10:22 UTC, tnagorra commented on app/src/views/OperationalLearning/Filters/index.tsx
> +    [K in keyof T]-?: [
Is this type used anymore?

2024-10-08 10:22 UTC, tnagorra commented on app/src/hooks/useRecursiveCsvRequest.ts
> +            onSuccess(data, total);
We need to update this.

2024-10-15 09:10 UTC, tnagorra approved these changes

2024-10-15 09:13 UTC, merged