Feature/emergency additional tab
IFRCGo/go-web-app pull request #138
Opened 2023-09-07 06:13 UTC by shreeyash07

## Addresses:
-  [Emergency Additional Tab](https://github.com/orgs/toggle-corp/projects/8/views/21?pane=issue&itemId=29928562)

## Changes
- Add dynamic additional tab in emergencies page

## This PR doesn't introduce:
- [x] typos
- [x] conflict markers
- [x] unwanted comments
- [x] temporary files, auto-generated files or secret keys
- [x] `console.log` meant for debugging
- [x] codegen errors

2023-09-07 08:06 UTC, samshara commented on src/views/Emergency/index.tsx
> +                ))}
we need to pass `key` prop here.

2023-09-07 08:06 UTC, samshara commented on src/views/EmergencyAdditionalTab/index.tsx
> +            ))}
we need to pass `key` prop here as well

2023-09-09 10:07 UTC, tnagorra requested changes

2023-09-09 10:07 UTC, tnagorra commented on src/views/Emergency/index.tsx
> +function routeName(text: string | null | undefined) {
```suggestion
function getRouteIdFromName(text: string) {
```

2023-09-09 10:07 UTC, tnagorra commented on src/views/EmergencyAdditionalTab/index.tsx
> +            {additionalTab?.snippets?.map((sanitize) => (
```suggestion
            {additionalTab?.snippets?.map((snippet) => (
```

2023-09-09 10:30 UTC, merged