Use DistrictSearchMultiSelectInput in Dref forms
IFRCGo/go-web-app pull request #142
Opened 2023-09-07 10:49 UTC by shreeyash07

## Addresses:
- XXX

## Changes
Replace MultiSelectInput with DistrictSeachMultiSelectInput in 
  - DrefApplicationForm
  - DrefFinalReportForm
  - DrefOperationalUpdateForm

## This PR doesn't introduce:
- [x] typos
- [x] conflict markers
- [x] unwanted comments
- [x] temporary files, auto-generated files or secret keys
- [x] `console.log` meant for debugging
- [x] codegen errors

2023-09-08 03:12 UTC, frozenhelium requested changes
Lets remove all unused variables
Please also do a `yarn lint` and `yarn typecheck` and fix all the issues before the PR.

2023-09-08 03:12 UTC, frozenhelium commented on src/views/DrefApplicationForm/Overview/index.tsx
> +} from '#components/domain/DistrictSearchMultiSelectInput';
Let's avoid using prettier on file level
```suggestion
import DistrictSearchMultiSelectInput, {
    type DistrictItem,
} from '#components/domain/DistrictSearchMultiSelectInput';
```

2023-09-08 03:12 UTC, frozenhelium commented on src/views/DrefFinalReportForm/Overview/index.tsx
> +} from '#components/domain/DistrictSearchMultiSelectInput';
```suggestion
import DistrictSearchMultiSelectInput, {
    type DistrictItem,
} from '#components/domain/DistrictSearchMultiSelectInput';
```

2023-09-08 03:12 UTC, frozenhelium commented on src/views/DrefOperationalUpdateForm/Overview/index.tsx
> +} from '#components/domain/DistrictSearchMultiSelectInput';
```suggestion
import DistrictSearchMultiSelectInput, {
    type DistrictItem,
} from '#components/domain/DistrictSearchMultiSelectInput';
```

2023-09-09 10:46 UTC, tnagorra approved these changes

2023-09-09 10:47 UTC, merged