Emergency activity page
IFRCGo/go-web-app pull request #150
Opened 2023-09-09 08:42 UTC by samshara

## This PR doesn't introduce:
- [x] typos
- [x] conflict markers
- [x] unwanted comments
- [x] temporary files, auto-generated files or secret keys
- [x] `console.log` meant for debugging
- [x] codegen errors

2023-09-09 12:23 UTC, tnagorra requested changes

2023-09-09 12:23 UTC, tnagorra commented on src/views/EmergencyActivities/ActivityDetail/styles.module.css
> +
```suggestion
```

2023-09-09 12:23 UTC, tnagorra commented on src/views/EmergencyActivities/ActivityDetail/index.tsx
> +                        <DateOutput value={project.end_date} className={styles.date} />
Let's break these down into different lines

2023-09-09 12:23 UTC, tnagorra commented on src/components/domain/DistrictMultiCountrySearchMultiSelectInput.tsx
What is the component supposed to do?

2023-09-09 12:23 UTC, tnagorra commented on src/components/domain/DistrictMultiCountrySearchMultiSelectInput.tsx
Feels like Java. :)

2023-09-09 12:23 UTC, tnagorra commented on src/views/EmergencyActivities/index.tsx
> +            ),
Let's create a separate Action component

2023-09-10 04:33 UTC, samshara commented on src/components/domain/DistrictMultiCountrySearchMultiSelectInput.tsx
select districts for multiple countries

2023-09-10 16:34 UTC, frozenhelium approved these changes

2023-09-10 16:36 UTC, merged