Update pull request template and issue templates
IFRCGo/go-web-app pull request #1580
Opened 2024-12-09 10:15 UTC by samshara

## Addresses:
- https://github.com/IFRCGo/go-web-app/issues/1579

## Changes
- Add new PR template.
- Add issue template for bug, feature and epic request.

## This PR doesn't introduce:
- [x] typos
- [x] conflict markers
- [x] unwanted comments
- [x] temporary files, auto-generated files or secret keys
- [x] `console.log` meant for debugging
- [x] codegen errors

2024-12-20 04:48 UTC, frozenhelium approved these changes

2024-12-20 06:09 UTC, barshathakuri approved these changes

2024-12-24 06:13 UTC, tnagorra commented on .github/pull_request_template.md
> +- [ ] `pnpm build` completes successfully
Should we merge this into "CI is passing" instead?

2024-12-24 06:30 UTC, tnagorra requested changes

2024-12-24 06:30 UTC, tnagorra commented on .github/ISSUE_TEMPLATE/01_bug_report.md
The file should be yaml

2024-12-24 06:30 UTC, tnagorra commented on .github/ISSUE_TEMPLATE/02_feature_request.md
The file should be yaml

2024-12-24 06:30 UTC, tnagorra commented on .github/ISSUE_TEMPLATE/03_epic_request.md
The file should be yaml

2024-12-24 06:30 UTC, tnagorra commented on .github/ISSUE_TEMPLATE/01_bug_report.md
> +labels: ['type: bug']
We should also add type "Bug". Not sure if issue forms support it yet.

2024-12-24 06:30 UTC, tnagorra commented on .github/ISSUE_TEMPLATE/02_feature_request.md
> +labels: ['type: feature-request']
We should also add type "Feature". Not sure if issue forms support it yet.

2024-12-24 06:30 UTC, tnagorra commented on .github/ISSUE_TEMPLATE/03_epic_request.md
> +labels: ['type: epic']
We should also add type "Feature". Not sure if issue forms support it yet.

2024-12-24 06:30 UTC, tnagorra commented on .github/ISSUE_TEMPLATE/01_bug_report.md
> +    attributes:
IMO we need a expected behavior vs actual behavior

2024-12-26 12:06 UTC, frozenhelium approved these changes

2024-12-26 12:16 UTC, tnagorra approved these changes

2024-12-26 12:16 UTC, merged