Local unit changes modal
IFRCGo/go-web-app pull request #1584
Opened 2024-12-12 05:15 UTC by shreeyash07

- Add function to get changes name and value
    - Add new file for key and label of the field

## Addresses:
- XXX

## Depends on:
- XXX

## Changes
- Detailed list or prose of changes
- Breaking changes
- Changes to configurations

## This PR doesn't introduce:
- [ ] typos
- [ ] conflict markers
- [ ] unwanted comments
- [ ] temporary files, auto-generated files or secret keys
- [ ] `console.log` meant for debugging
- [ ] codegen errors

2024-12-17 08:38 UTC, tnagorra requested changes

2024-12-17 08:38 UTC, tnagorra commented on app/src/utils/common.ts
> +}
Either the comparison is no correct or the name of the function is not correct.

2024-12-17 08:38 UTC, tnagorra commented on app/src/utils/common.ts
> +}
Does this not handle array elements?

2024-12-17 08:38 UTC, tnagorra commented on app/src/views/CountryNsOverviewContextAndStructure/NationalSocietyLocalUnits/LocalUnitsFormModal/LocalUnitsForm/index.tsx
> +        }
Let's just use isNotDefined

2024-12-17 08:38 UTC, tnagorra commented on app/src/views/CountryNsOverviewContextAndStructure/NationalSocietyLocalUnits/LocalUnitsFormModal/LocalUnitsForm/index.tsx
> +    const flattenedOldValues = flattenObject(oldValues);
I am not sure if we can use this approach. This fails if/when we have array elements.

2024-12-17 08:38 UTC, tnagorra commented on app/src/views/CountryNsOverviewContextAndStructure/NationalSocietyLocalUnits/LocalUnitsFormModal/LocalUnitsForm/index.tsx
> +                    health_facility_type: health?.health_facility_type,
Any reason to write these out individually? Why not just spread this out?

2024-12-17 08:38 UTC, tnagorra commented on app/src/views/CountryNsOverviewContextAndStructure/NationalSocietyLocalUnits/LocalUnitsFormModal/LocalUnitsForm/index.tsx
> +                setLocalUnitChangedFormFields(() => changedFormFields);
```suggestion
                setLocalUnitChangedFormFields(changedFormFields);
```

2024-12-17 08:38 UTC, tnagorra commented on app/src/views/CountryNsOverviewContextAndStructure/NationalSocietyLocalUnits/LocalUnitsFormModal/LocalUnitsForm/useLocalUnitFormFieldLabels.ts
> +function useLocalUnitFormFieldLabels(props: Props) {
Are these created just to display the labels on diff mode?

2024-12-17 08:40 UTC, shreeyash07 commented on app/src/views/CountryNsOverviewContextAndStructure/NationalSocietyLocalUnits/LocalUnitsFormModal/LocalUnitsForm/useLocalUnitFormFieldLabels.ts
> +function useLocalUnitFormFieldLabels(props: Props) {
Yes.

2024-12-17 08:43 UTC, shreeyash07 commented on app/src/views/CountryNsOverviewContextAndStructure/NationalSocietyLocalUnits/LocalUnitsFormModal/LocalUnitsForm/index.tsx
> +                    health_facility_type: health?.health_facility_type,
when we compare the value later, the comparison function checks for `_display` values. We don't need these values for form fields. So we didn't spread them out.

2024-12-17 08:43 UTC, shreeyash07 commented on app/src/views/CountryNsOverviewContextAndStructure/NationalSocietyLocalUnits/LocalUnitsFormModal/LocalUnitsForm/index.tsx
> +    const flattenedOldValues = flattenObject(oldValues);
we will refactor this later. will add a TODO

2024-12-17 08:43 UTC, shreeyash07 commented on app/src/utils/common.ts
> +}
we will refactor this later. will add a TODO

2024-12-17 09:02 UTC, AdityaKhatri requested changes

2024-12-17 09:02 UTC, AdityaKhatri commented on app/src/utils/common.ts
> +}
write tests

2024-12-17 09:02 UTC, AdityaKhatri commented on app/src/utils/common.ts
> +export function compareArrays(newArray: unknown[], oldArray: unknown[]): boolean {
```suggestion
export function isArraySame(newArray: unknown[], oldArray: unknown[]): boolean {
```

2024-12-17 09:02 UTC, AdityaKhatri commented on app/src/views/CountryNsOverviewContextAndStructure/NationalSocietyLocalUnits/LocalUnitsFormModal/LocalUnitsForm/index.tsx
> +) {
Write return type
```suggestion
function getChangedFormFields(
    newValues: PartialLocalUnits,
    oldValues: LocalUnitResponse,
    formFieldOptions: LocalUnitOptions,
): { key: string; value: string }[] {
```

2024-12-17 09:02 UTC, AdityaKhatri commented on app/src/views/CountryNsOverviewContextAndStructure/NationalSocietyLocalUnits/LocalUnitsFormModal/LocalUnitsForm/index.tsx
> +        }
add few comments on what is being done to make it more readable

2024-12-17 09:02 UTC, AdityaKhatri commented on app/src/views/CountryNsOverviewContextAndStructure/NationalSocietyLocalUnits/LocalUnitsFormModal/LocalUnitsForm/index.tsx
> +function getChangedFormFields(
Write tests

2024-12-17 09:02 UTC, AdityaKhatri commented on app/src/views/CountryNsOverviewContextAndStructure/NationalSocietyLocalUnits/LocalUnitsFormModal/LocalUnitsForm/index.tsx
> +                setLocalUnitChangedFormFields(() => changedFormFields);
```suggestion
                setLocalUnitChangedFormFields(changedFormFields);
```

2024-12-17 13:18 UTC, samshara commented on app/src/utils/common.ts
> +}
Added a `TODO` comment.

2024-12-18 04:58 UTC, AdityaKhatri approved these changes

2024-12-18 05:29 UTC, merged