Localunits delete modal
IFRCGo/go-web-app pull request #1587
Opened 2024-12-13 10:13 UTC by shreeyash07

## Addresses:
- #1497 

## Changes
- Add modal for localunits deletion in localunit table and localunit form
- Update delete localunits api 

## This PR doesn't introduce:
- [x] typos
- [x] conflict markers
- [x] unwanted comments
- [x] temporary files, auto-generated files or secret keys
- [x] `console.log` meant for debugging
- [x] codegen errors

2024-12-16 04:52 UTC, tnagorra requested changes

2024-12-16 04:52 UTC, tnagorra commented on app/src/views/CountryNsOverviewContextAndStructure/NationalSocietyLocalUnits/LocalUnitsTable/LocalUnitTableActions/index.tsx
> +    );
We don't need to define this function. We can directly pass `setShowDeleteLocalUnitModalTrue` where `hanldeDeleteLocalUnitClick` is used

2024-12-16 04:52 UTC, tnagorra commented on app/src/views/CountryNsOverviewContextAndStructure/NationalSocietyLocalUnits/LocalUnitsTable/LocalUnitTableActions/index.tsx
> +    const { isAuthenticated: handleDeletePermission } = useAuth();
This rename is not correct.

2024-12-16 04:52 UTC, tnagorra commented on app/src/views/CountryNsOverviewContextAndStructure/NationalSocietyLocalUnits/LocalUnitsFormModal/LocalUnitsForm/index.tsx
> +    );
We don't need to define this function. We can just use setShowDeleteLocalUnitModalTrue

2024-12-16 04:52 UTC, tnagorra commented on app/src/views/CountryNsOverviewContextAndStructure/NationalSocietyLocalUnits/LocalUnitDeleteModal/index.tsx
> +    const { isAuthenticated: hasDeletePermission } = useAuth();
This rename is not correct.

2024-12-16 04:52 UTC, tnagorra commented on app/src/views/CountryNsOverviewContextAndStructure/NationalSocietyLocalUnits/LocalUnitDeleteModal/index.tsx
> +    localUnitName: string | null | undefined;
Shouldn't this always be defined when we are deleting a local unit? It should always have a name.

2024-12-16 06:46 UTC, tnagorra commented on app/src/views/CountryNsOverviewContextAndStructure/NationalSocietyLocalUnits/LocalUnitDeleteModal/index.tsx
> +    const hasDeletePermission = isAuthenticated;
This is still and issue. The way it was renamed was not the isssue.
The issue is regarding the logic.
Do we not have permissions defined on the server on what a user can perform?
Not all authenticated user should have delete permission.
example: we have guest users who can login but cannot perform any operation.

2024-12-16 06:48 UTC, tnagorra requested changes

2024-12-16 06:48 UTC, tnagorra commented on app/src/views/CountryNsOverviewContextAndStructure/NationalSocietyLocalUnits/LocalUnitsTable/LocalUnitTableActions/index.tsx
> +    const hasDeletePermission = isAuthenticated;
This is still and issue. The way it was renamed was not the isssue.
The issue is regarding the logic.
Do we not have permissions defined on the server on what a user can perform?
Not all authenticated user should have delete permission.
example: we have guest users who can login but cannot perform any operation.

2024-12-16 06:48 UTC, tnagorra commented on app/src/views/CountryNsOverviewContextAndStructure/NationalSocietyLocalUnits/LocalUnitDeleteModal/index.tsx
> +                { localUnitName: localUnitName ?? '' },
We can remove this fallback value as localUnitName is always string

2024-12-17 04:05 UTC, samshara approved these changes

2024-12-17 04:17 UTC, tnagorra approved these changes

2024-12-17 04:57 UTC, merged