Fix the normalization logic in seasonal risk
IFRCGo/go-web-app pull request #1592
Opened 2024-12-19 07:18 UTC by frozenhelium

- Add option to include Lack of Coping capacity for Risk score
- Remove option to include Lack of Coping capacity for People exposed and People at Risk of Displacement

## Addresses:

- https://github.com/IFRCGo/go-web-app/issues/1545

2024-12-20 06:06 UTC, barshathakuri approved these changes

2024-12-20 06:06 UTC, barshathakuri commented on app/src/views/CountryProfileRiskWatch/MultiMonthSelectInput/index.tsx
> +import { monthKeyList, multiMonthSelectDefaultValue } from '#utils/constants';
Lint errors.

2024-12-24 04:20 UTC, tnagorra requested changes

2024-12-24 04:20 UTC, tnagorra commented on app/src/components/domain/RiskSeasonalMap/index.tsx
> +            ) ?? 1;
What if this sumSafe is zero?

2024-12-24 04:26 UTC, tnagorra requested changes

2024-12-24 04:26 UTC, tnagorra commented on app/src/views/CountryProfileRiskWatch/index.tsx
> +    });
The default month is not selected. Is there any other requirement?

2024-12-24 04:38 UTC, tnagorra commented on app/src/components/domain/RiskSeasonalMap/index.tsx
> +                (result) => 1 - (result.population_in_thousands / totalPopulation) ** (1 / 4),
Do we have any reference for using this metric?

2024-12-24 05:57 UTC, tnagorra commented on app/src/components/domain/RiskSeasonalMap/index.tsx
> +                (result) => 1 - (result.population_in_thousands / totalPopulation) ** (1 / 4),
Added a NOTE regarding this metric.

2024-12-24 05:58 UTC, tnagorra approved these changes

2024-12-24 06:00 UTC, tnagorra commented on app/src/views/CountryProfileRiskWatch/index.tsx
> +    });
It is selected only after the data is fetched from the server.

NOTE: This change is for a country profile risk watch while the other change is for global risk watch.

2024-12-24 06:11 UTC, merged