Add missing links and fix some minor UI issues
IFRCGo/go-web-app pull request #160
Opened 2023-09-11 17:26 UTC by barshathakuri

## Changes
- Add missing links in surge overview
- Fix minor UI issues

## This PR doesn't introduce:
- [x] typos
- [x] conflict markers
- [x] unwanted comments
- [x] temporary files, auto-generated files or secret keys
- [x] `console.log` meant for debugging
- [x] codegen errors

2023-09-12 01:34 UTC, frozenhelium requested changes
Looks good, one small change!

2023-09-12 01:34 UTC, frozenhelium commented on src/App/routes/index.tsx
> +    path: 'about',
Let's keep the path as 'resources' and mark this as "Intentional" change

2023-09-12 13:58 UTC, tnagorra approved these changes

2023-09-13 02:31 UTC, frozenhelium approved these changes

2023-09-13 02:37 UTC, merged