Hide and unhide sections
IFRCGo/go-web-app pull request #1615
Opened 2024-12-27 11:04 UTC by barshathakuri

## Summary
Dref Imminent few sections have been removed

## Addresses
- #1610 

## Changes
- Hide sections
- Change in dref Export

## This PR Ensures:
- [x] No typos or grammatical errors
- [x] No conflict markers left in the code
- [x] No unwanted comments, temporary files, or auto-generated files
- [x] No inclusion of secret keys or sensitive data
- [x] No `console.log` statements meant for debugging
- [x] All CI checks have passed

## Additional Notes
- These changes in dref export is remaining.

2024-12-30 06:18 UTC, shreeyash07 approved these changes

2024-12-30 06:32 UTC, AdityaKhatri approved these changes
LGTM from technical perspective but needs to be checked from logical perspective by @samshara and @shreeyash07 .

2024-12-30 09:32 UTC, samshara approved these changes

2024-12-30 09:32 UTC, samshara commented on app/src/views/DrefApplicationExport/i18n.json
> +        "exportDrefImminentTitle": "Imminent DREF operation",
```suggestion
        "exportDrefImminentTitle": "Imminent DREF Operation",
```

2025-01-09 10:02 UTC, samshara requested changes

2025-01-09 10:02 UTC, samshara commented on app/src/components/domain/DrefExportModal/index.tsx
> +                                    onClick={handleDownload}
We don't need this

2025-01-09 10:02 UTC, samshara commented on app/src/components/domain/DrefExportModal/index.tsx
> +
We don’t need this. The link already opens and downloads the file automatically because the server includes the `Content-Disposition: attachment` header with the file. If not the server should include the above header.

2025-01-09 10:02 UTC, samshara commented on app/src/views/DrefApplicationExport/index.tsx
> +    const showPreviousOperations = drefResponse?.type_of_dref === DREF_TYPE_RESPONSE && (
is this valid?

2025-01-09 10:02 UTC, samshara commented on app/src/views/DrefApplicationExport/index.tsx
> +        (is_pga) => (is_pga ? 'true' : undefined),
is this correct?

2025-01-09 10:02 UTC, samshara commented on app/src/views/DrefApplicationExport/index.tsx
> +    const [pgaExport] = useUrlSearchState<true | undefined>(
we could have just say the return value is boolean and returned false.

2025-01-20 09:46 UTC, barshathakuri commented on app/src/views/DrefApplicationExport/index.tsx
> +    const showPreviousOperations = drefResponse?.type_of_dref === DREF_TYPE_RESPONSE && (
The `showPreviousOperations` field is displayed only for the response type in the form. Therefore, I have updated it exclusively for the response type in the export.

2025-01-20 09:46 UTC, barshathakuri commented on app/src/views/DrefApplicationExport/index.tsx
> +    const showPreviousOperations = drefResponse?.type_of_dref === DREF_TYPE_RESPONSE && (
@samshara

2025-01-28 06:12 UTC, shreeyash07 requested changes

2025-01-28 06:12 UTC, shreeyash07 commented on app/src/views/DrefApplicationForm/Overview/index.tsx
> +        }
we can use setValue for this so we can write condition inside.

2025-01-28 06:12 UTC, shreeyash07 commented on app/src/components/domain/DrefExportModal/index.tsx
> +
No need remove this

2025-01-28 06:12 UTC, shreeyash07 commented on app/src/components/domain/DrefExportModal/index.tsx
> +                is_pga: undefined,
use direct is_pga value

2025-01-28 08:37 UTC, AdityaKhatri requested changes
Looks good to me logic wise. Someone needs to check the business logic though.

2025-01-28 08:37 UTC, AdityaKhatri commented on app/src/components/domain/DrefExportModal/index.tsx
> +            }
show an alert in case of error while creating the export

2025-01-28 08:43 UTC, samshara requested changes

2025-01-28 08:43 UTC, samshara commented on app/src/components/domain/DrefExportModal/index.tsx
>      const {
We should block this request when dref is imminent dref

2025-01-28 08:43 UTC, samshara commented on app/src/components/domain/DrefExportModal/index.tsx
> +        query: { is_pga: isPga } as unknown as { format?: 'csv' | 'json'; },
Let's remove this. This doesn't do anything.

2025-01-28 08:43 UTC, samshara commented on app/src/components/domain/DrefExportModal/index.tsx
> +        error: exportDrefTriggerError,
```suggestion
        pending: imminentDrefExportTriggerPending,
        error: imminentDrefExportTriggerError,
```

2025-01-28 08:43 UTC, samshara commented on app/src/components/domain/DrefExportModal/index.tsx
> +                        </div>
Let's remove this additional div

2025-01-28 08:43 UTC, samshara commented on app/src/views/AccountMyFormsDref/DrefTableActions/index.tsx
> +    drefType?: TypeOfDrefEnum | null;
```suggestion
    drefType: TypeOfDrefEnum | null | undefined;
```

2025-01-28 08:43 UTC, samshara commented on app/src/views/DrefApplicationForm/Overview/index.tsx
> +                            }
This is not required.

2025-01-28 08:43 UTC, samshara commented on app/src/views/DrefApplicationExport/index.tsx
> +    isTruthyString(drefResponse?.event_description?.trim());
what does this do?

2025-01-28 08:43 UTC, samshara commented on app/src/views/DrefApplicationExport/index.tsx
> +                        />
we could use a div here

2025-01-28 08:43 UTC, samshara commented on app/src/views/DrefApplicationExport/index.tsx
> +                                </ul>
we need a key here

2025-01-28 08:43 UTC, samshara commented on app/src/views/DrefApplicationExport/index.tsx
> +                                            label=""
do we need this?

2025-01-28 08:43 UTC, samshara commented on app/src/views/DrefApplicationExport/index.tsx
> +                                />
we need to pass key

2025-01-28 08:43 UTC, samshara commented on app/src/views/DrefApplicationExport/index.tsx
> +                                </ul>
we need to pass key here

2025-01-28 08:43 UTC, samshara commented on app/src/views/DrefApplicationExport/index.tsx
> +                                            label=""
we don't need label here

2025-01-28 08:43 UTC, samshara commented on app/src/views/DrefApplicationExport/index.tsx
> +                                />
we need to pass key here

2025-01-28 08:43 UTC, samshara commented on app/src/views/DrefApplicationExport/index.tsx
> +                        />
we can use div here

2025-01-28 08:43 UTC, samshara commented on app/src/views/DrefApplicationExport/index.tsx
> +                        />
we can use div here

2025-01-28 08:43 UTC, samshara commented on app/src/views/DrefApplicationExport/index.tsx
> +                        />
we can use div here

2025-01-28 08:43 UTC, samshara commented on app/src/views/DrefApplicationExport/index.tsx
> +                        />
we can use div here

2025-01-28 08:43 UTC, samshara commented on app/src/views/DrefApplicationExport/index.tsx
> +                    Proposed Actions
Let's use string translations here

2025-01-28 08:43 UTC, samshara commented on app/src/views/DrefApplicationExport/index.tsx
> +            <div className={styles.pageBreak} />
Let's move this inside pgaExport

2025-01-31 04:42 UTC, shreeyash07 approved these changes

2025-01-31 05:04 UTC, samshara approved these changes

2025-01-31 05:52 UTC, merged