Add link and fix styling
IFRCGo/go-web-app pull request #173
Opened 2023-09-13 11:25 UTC by barshathakuri

## Changes
- Add links
- Fix styling

## This PR doesn't introduce:
- [x] typos
- [x] conflict markers
- [x] unwanted comments
- [x] temporary files, auto-generated files or secret keys
- [x] `console.log` meant for debugging
- [x] codegen errors

2023-09-13 11:51 UTC, shreeyash07 approved these changes

2023-09-13 12:36 UTC, samshara approved these changes

2023-09-13 16:40 UTC, frozenhelium approved these changes

2023-09-14 12:03 UTC, tnagorra requested changes

2023-09-14 12:03 UTC, tnagorra commented on src/views/AllAppeals/index.tsx
> -                    sortable: true,
Let's not remove this.

2023-09-14 12:03 UTC, tnagorra commented on src/views/FieldReportDetails/index.tsx
> +                        {eventDetails?.id && (
```suggestion
                        {eventDetails && (
```

2023-09-14 12:08 UTC, merged