Minor Fixes
IFRCGo/go-web-app pull request #187
Opened 2023-09-19 05:26 UTC by shreeyash07

## Changes
- fix navigation option in useUrlSearchState
- add missing sortable in AllFlashUpdate
- add missing query in AllThreeWProject
- Update strings

## This PR doesn't introduce:
- [x] typos
- [x] conflict markers
- [x] unwanted comments
- [x] temporary files, auto-generated files or secret keys
- [x] `console.log` meant for debugging
- [x] codegen errors

2023-09-19 11:20 UTC, barshathakuri requested changes

2023-09-19 11:20 UTC, barshathakuri commented on src/views/CountryThreeWNationalSocietyProjects/index.tsx
> +                            // urlParams={{ reporting_ns: countryResponse?.id }}
Please remove unwanted comments

2023-09-19 17:18 UTC, frozenhelium commented on src/hooks/useUrlSearchState.ts
> +    navigateOptions?: NavigateOptions,
What's the purpose of this change?

2023-09-19 17:18 UTC, frozenhelium commented on src/views/AllThreeWProject/index.tsx
> +        (reportingNS) => reportingNS,
```suggestion
        (reportingNs) => reportingNs,
```

2023-09-20 13:08 UTC, frozenhelium approved these changes

2023-09-20 13:12 UTC, merged