Fix high priority tasks
IFRCGo/go-web-app pull request #188
Opened 2023-09-19 11:17 UTC by barshathakuri

## Changes
- Add Region 3W component
- Add icon for wildfire
- Add pending in login 
- Fix links in 3W

## This PR doesn't introduce:
- [x] typos
- [x] conflict markers
- [x] unwanted comments
- [x] temporary files, auto-generated files or secret keys
- [x] `console.log` meant for debugging
- [x] codegen errors

2023-09-19 14:47 UTC, tnagorra approved these changes

2023-09-19 14:47 UTC, tnagorra commented on src/components/domain/RegionDropdown/i18n.json
> +    "namespace": "regionDropdown",
```suggestion
    "namespace": "common",
```

2023-09-19 14:47 UTC, tnagorra commented on src/views/GlobalThreeW/Map/i18n.json
> +    "namespace": "globalThreeWMap",
```suggestion
    "namespace": "globalThreeW",
```

2023-09-20 05:15 UTC, shreeyash07 approved these changes

2023-09-20 13:23 UTC, frozenhelium requested changes

2023-09-20 13:23 UTC, frozenhelium commented on src/components/domain/RiskImminentEvents/index.tsx
> +        />,
We should use icon from the GO Icons

2023-09-20 13:23 UTC, frozenhelium commented on src/components/domain/Region3WDropdown/index.tsx
This component can be localized to the Global 3W view

2023-09-20 13:23 UTC, frozenhelium commented on src/components/domain/Region3WDropdown/i18n.json
> +    "namespace": "region3WDropdown",
Probably should use "threeW" namespace

2023-09-20 13:38 UTC, frozenhelium approved these changes

2023-09-20 13:42 UTC, merged