Fix PER assessment and prioritization form according to new form stan…
IFRCGo/go-web-app pull request #191
Opened 2023-09-20 09:29 UTC by barshathakuri

## Changes
- Add Disabled
- Add error
- Add NonFieldError

## This PR doesn't introduce:
- [x] typos
- [x] conflict markers
- [x] unwanted comments
- [x] temporary files, auto-generated files or secret keys
- [x] `console.log` meant for debugging
- [x] codegen errors

2023-09-20 11:20 UTC, shreeyash07 approved these changes

2023-09-21 05:17 UTC, shreeyash07 approved these changes

2023-09-21 05:25 UTC, tnagorra requested changes

2023-09-21 05:25 UTC, tnagorra commented on src/views/PerPrioritizationForm/ComponentInput/index.tsx
> +                            {`${numResponses} ${strings.benchmarksAssessed}`}
We still might need to use translation here

2023-09-21 05:52 UTC, samshara approved these changes

2023-09-21 06:45 UTC, merged