Add index routes to region and account page
IFRCGo/go-web-app pull request #22
Opened 2023-06-09 05:49 UTC by frozenhelium

2023-06-16 05:49 UTC, priyesh777 approved these changes

2023-06-19 06:54 UTC, tnagorra requested changes

2023-06-19 06:54 UTC, tnagorra commented on src/components/ReducedListDisplay/index.tsx
> +    const reducer = useCallback(
Let's just use useMemo and generate the allJoinedList instead

2023-06-19 06:54 UTC, tnagorra commented on src/utils/emergency.ts
> +    )[0];
This will mutate the object inside the argument.

2023-06-19 06:54 UTC, tnagorra commented on src/views/Emergencies/index.tsx
> +                        labelSelector={(groupedEvent) => groupedEvent.typeName}
Let's not define inline functions on jsx

2023-06-19 06:54 UTC, tnagorra commented on src/views/Emergencies/index.tsx
> +                            classNameSelector={() => styles.eventsChart}
Let's not define inline functions on jsx

2023-06-19 06:54 UTC, tnagorra commented on src/views/Emergencies/index.tsx
> +    );
Let's also memoize these

2023-06-19 06:54 UTC, tnagorra commented on src/views/Search/EmergencyTable/index.tsx
> +            (item) => ({
We should create a separate column type instead of passing a function to render custom blocks.

2023-06-19 06:54 UTC, tnagorra commented on src/views/Emergencies/FlashUpdatesTable/index.tsx
> +                    )),
We should create a separate component for this.

2023-06-19 06:54 UTC, tnagorra commented on src/views/Emergencies/FieldReportsTable/index.tsx
> +                </Link>
Why are we linking to home page?

2023-06-19 06:54 UTC, tnagorra commented on src/views/Emergencies/FieldReportsTable/index.tsx
> +                    )),
We should create a separate component for this.

2023-06-19 06:54 UTC, tnagorra commented on src/views/Emergencies/EmergenciesTable/index.tsx
> +                    )),
We should create a separate component for this.

2023-06-19 06:54 UTC, tnagorra commented on src/views/Emergencies/EmergenciesTable/index.tsx
> +                ),
Can we instead pre-compute this?

2023-06-19 06:54 UTC, tnagorra commented on src/views/Emergencies/Map/index.tsx
> +    ]), [strings]);
Let's just create two separate useMemo

2023-06-19 06:54 UTC, tnagorra commented on src/views/Emergencies/Map/index.tsx
> +                        if (!groupedEvents[0].country.centroid || !groupedEvents[0].country.iso3) {
Let's assign groupedEvents[0].country to a separate variable.

2023-06-19 06:54 UTC, tnagorra commented on src/views/Emergencies/Map/index.tsx
> +                    to="/"
Why are we linking to home page?

2023-06-19 13:27 UTC, merged