Revamp the register page inaccordance to the new UI guidelines
IFRCGo/go-web-app pull request #23
Opened 2023-06-19 10:30 UTC by priyesh777

## Addresses:
- Issue: 

## Changes:
- Add new UI structure to the register page 

## This PR doesn't introduce:
- [x] typos
- [x] conflict markers
- [x] unwanted comments
- [x] temporary files, auto-generated files or secret keys
- [x] `console.log` meant for debugging
- [x] codegen errors

2023-06-26 09:00 UTC, frozenhelium approved these changes

2023-06-26 09:00 UTC, frozenhelium commented on src/views/Register/index.tsx
> +        },
we don't need to explicitly specify `required: false`

2023-06-26 09:00 UTC, frozenhelium commented on src/views/Register/index.tsx
> +            const message = 'Sorry could not register new user right now !';
Use translation

2023-06-26 09:00 UTC, frozenhelium commented on src/views/Register/index.tsx
> +            const message = 'Successfully created a user !';
Use translation

2023-06-26 10:08 UTC, tnagorra requested changes

2023-06-26 10:08 UTC, tnagorra commented on src/views/Register/index.tsx
> +            requiredCondition,
```suggestion
            requiredCondition: requiredStringCondition,
```

2023-06-26 10:08 UTC, tnagorra commented on src/views/Register/index.tsx
> +            requiredCondition,
Let's also add email validation

2023-06-26 10:08 UTC, tnagorra commented on src/views/Register/index.tsx
> +            requiredCondition,
```suggestion
```

2023-06-26 10:08 UTC, tnagorra commented on src/views/Register/index.tsx
> +            requiredCondition,
```suggestion
```

2023-06-26 10:08 UTC, tnagorra commented on src/views/Register/index.tsx
> +        },
Let's add a validation to check if password and confirmPassword match

2023-06-26 10:08 UTC, tnagorra commented on src/views/Register/index.tsx
> +            navigate('/login');
Do not directly use url on navigate

2023-06-26 10:08 UTC, tnagorra commented on src/views/Register/index.tsx
> +        setCountryName(countrySelected);
We do not need this state.

2023-06-26 10:08 UTC, tnagorra commented on src/views/Register/index.tsx
> +        setOrganizationType(org);
We do not need this state.

2023-06-26 10:08 UTC, tnagorra commented on src/views/Register/index.tsx
> +    ]);
Let's use createSubmitHandler here

2023-06-29 02:00 UTC, frozenhelium requested changes
- Verify conditional fields
- Improve styling with grid

2023-06-29 02:00 UTC, frozenhelium commented on src/views/Register/index.tsx
> +                <div className={styles.fields}>
We don't need intermediate `div` elements when using `display: grid`

2023-06-29 02:00 UTC, frozenhelium commented on src/views/Register/index.tsx
> +                <TextInput
This field type changes conditionally

2023-06-29 02:00 UTC, frozenhelium commented on src/views/Register/index.tsx
> +            (country) => isValidCountry(country) && !!country.name,
lets add `isTruthyString(country.name)` to the `isValidCountry` util itself

2023-06-29 02:00 UTC, frozenhelium commented on src/views/Register/index.tsx
> +            setError(formErrors);
We should transform error to match the format of formErrors

2023-06-29 02:00 UTC, frozenhelium commented on src/views/Register/index.tsx
> +interface ResponseFields {
Let's add this to `serverResponse.ts` @tnagorra

2023-07-04 02:03 UTC, frozenhelium requested changes

2023-07-04 02:03 UTC, frozenhelium commented on src/types/serverResponse.ts
> +export interface RegisterResponseFields {
Remove `export` and move entry inside `GET`

2023-07-04 02:03 UTC, frozenhelium commented on src/views/Register/styles.module.css
> +        justify-content: center;
```suggestion
        justify-content: center;
        gap: var(--go-ui-spacing-4xl);
```

2023-07-04 02:03 UTC, frozenhelium commented on src/views/Register/styles.module.css
> +            gap: var(--go-ui-spacing-2xl);
`gap` will overwrite `grid-gap` when `display: grid` is used. Let's remove it and use `grid-gap`

2023-07-04 02:03 UTC, frozenhelium commented on src/views/Register/styles.module.css
> +            padding: var(--go-ui-spacing-3xl);
We can remove padding from here

2023-07-04 02:03 UTC, frozenhelium commented on src/views/Register/styles.module.css
> +                border: var(--go-ui-width-separator-sm) solid var(--go-ui-color-gray-20);
```suggestion
                border: var(--go-ui-width-separator-sm) solid var(--go-ui-color-separator);
```

2023-07-04 02:03 UTC, frozenhelium commented on src/views/Register/styles.module.css
> +                border: var(--go-ui-width-separator-sm) solid var(--go-ui-color-gray-20);
Better to use
```css
height: var(--go-ui-width-separator-sm);
background-color: var(--go-ui-color-separator);
```
instead of `border`

2023-07-04 02:03 UTC, frozenhelium commented on src/views/Register/styles.module.css
> +                gap: var(--go-ui-spacing-md);
```suggestion
                gap: var(--go-ui-spacing-xs);
```

2023-07-04 02:03 UTC, frozenhelium commented on src/views/Register/styles.module.css
> +                gap: var(--go-ui-spacing-md);
Also add `align-items: center`

2023-07-04 02:03 UTC, frozenhelium commented on src/views/Register/styles.module.css
> +            }
This styling is not required. Grid will automatically expand the size of input field when using `auto-fit`. And we should not overwrite the `font-weight` for inputs

2023-07-04 02:03 UTC, frozenhelium commented on src/views/Register/index.tsx
> +            return 'The passwords do not match.';
Use translations

2023-07-04 02:03 UTC, frozenhelium commented on src/views/Register/index.tsx
> +interface OptionType {
Naming for `OptionType` should be more specific to it's type

2023-07-04 02:03 UTC, frozenhelium commented on src/views/Register/index.tsx
> +    const { response: countriesResponse } = useRequest<ListResponse<Country>>({
```suggestion
    const { response: countriesResponse } = useRequest<GET['api/v2/country']>({
```

2023-07-04 02:03 UTC, frozenhelium commented on src/views/Register/index.tsx
> +    const handleOrganizationName = useCallback(
```suggestion
    const handleOrganizationNameChange = useCallback(
```

2023-07-04 02:03 UTC, frozenhelium commented on src/views/Register/index.tsx
> +    } = useLazyRequest<RegisterResponseFields, FormFields>({
```suggestion
    } = useLazyRequest<GET['register'], FormFields>({
```

2023-07-04 06:32 UTC, priyesh777 commented on src/views/Register/index.tsx
> +            setError(formErrors);
This has been ignored since new typings will be generated in the upcoming pull requests.

2023-07-04 08:52 UTC, tnagorra requested changes

2023-07-04 08:52 UTC, tnagorra commented on src/views/DrefApplicationForm/index.tsx
Let's remove the changes from DrefApplicationForm

2023-07-04 08:52 UTC, tnagorra commented on src/views/Register/i18n.json
> +        "registrationSuccess": "Successfully created a user !"
```suggestion
        "registrationSuccess": "Successfully created a user!"
```

2023-07-04 08:52 UTC, tnagorra commented on src/views/Register/i18n.json
> +        "registrationSuccess": "Successfully created a user !"
```suggestion
        "registrationFailure": "Sorry could not register new user right now!",
        "registrationSuccess": "Successfully created a user!"
```

2023-07-04 08:52 UTC, tnagorra commented on src/views/Register/index.tsx
> +    const formSchema: ObjectSchema<FormFields> = useMemo(
Let's move this outside the function.
We will handle translation of errors separately.

2023-07-04 08:52 UTC, tnagorra commented on src/views/Register/index.tsx
> +    );
Let's group usecallback, usememo and usestate

2023-07-04 08:52 UTC, tnagorra commented on src/views/Register/index.tsx
> +                )}
Let's use ternary operator

2023-07-06 12:08 UTC, frozenhelium approved these changes

2023-07-06 12:09 UTC, merged