Feature/list view pages
IFRCGo/go-web-app pull request #24
Opened 2023-06-20 03:19 UTC by frozenhelium

2023-06-21 04:26 UTC, priyesh777 approved these changes

2023-06-21 11:20 UTC, priyesh777 approved these changes

2023-06-23 04:29 UTC, priyesh777 approved these changes

2023-06-26 10:01 UTC, tnagorra requested changes

2023-06-26 10:01 UTC, tnagorra commented on src/components/Tooltip/index.tsx
> +            if (dummyRef.current) {
Let's return early. Also, let's not use parentRef.current on cleanup

2023-06-26 10:01 UTC, tnagorra commented on src/components/Tooltip/index.tsx
> +                />
Let's style this as fixed element with visibility hidden

2023-06-26 10:01 UTC, tnagorra commented on src/views/AllFieldReports/index.tsx
> +                    ),
These 2 should be memoized.

2023-06-26 10:01 UTC, tnagorra commented on src/views/AllFlashUpdates/index.tsx
> +            ),
These functions should be separately memoized

2023-06-26 10:01 UTC, tnagorra commented on src/views/Home/HighlightedOperations/OperationCard/index.tsx
> +    }
Let's simplify

2023-07-10 04:47 UTC, AdityaKhatri approved these changes

2023-07-10 04:47 UTC, merged