Add new changes to the account information
IFRCGo/go-web-app pull request #26
Opened 2023-06-23 11:20 UTC by priyesh777

## Addresses:
- Issue: https://github.com/toggle-corp/ifrc-go-meta/issues/155#issue-1741047013

## Changes:
- Add new UI changes to the account information tab of ACCOUNT section

## This PR doesn't introduce:
- [x] typos
- [x] conflict markers
- [x] unwanted comments
- [x] temporary files, auto-generated files or secret keys
- [x] `console.log` meant for debugging
- [x] codegen errors

2023-06-29 02:12 UTC, frozenhelium requested changes
- Fix all the linting issues
- Remove unused translations
- Rename components appropriately
- Let's use styling from https://www.figma.com/proto/u0XifdJwTEx165x3e0eoP9/IFRC-GO_UI-Prototype?type=design&node-id=673-6133&scaling=scale-down-width&page-id=0%3A4957&starting-point-node-id=0%3A4963&hide-ui=1
![2023-06-29-074828](https://github.com/IFRCGo/go-web-app/assets/4931541/7efb8568-78b5-4b1c-b8ad-5820e37df92d)

2023-06-29 02:12 UTC, frozenhelium commented on src/views/Account/AccountInfo/OperationInfoCard/i18n.json
> +        "operationFollowing": "operation following",
```suggestion
        "operationFollowing": "Operations following",
```

2023-06-29 02:12 UTC, frozenhelium commented on src/views/Account/AccountInfo/OperationInfoCard/i18n.json
> +        "operationLastUpdated": "last updated",
```suggestion
        "operationLastUpdated": "Last updated",
```

2023-06-29 02:12 UTC, frozenhelium commented on src/views/Account/AccountInfo/index.tsx
> +                    <div className={styles.userDetailSection}>
Use `TextOutput` component for these type of view

2023-06-29 02:12 UTC, frozenhelium commented on src/views/Account/AccountInfo/OperationInfoCard/i18n.json
> +        "operationFollowing": "operation following",
This is probably unused

2023-06-29 02:12 UTC, frozenhelium commented on src/views/Account/AccountInfo/index.tsx
> +interface UserResponse {
Let's move this to `serverResponse.ts`

2023-06-29 02:12 UTC, frozenhelium commented on src/views/Account/AccountInfo/i18n.json
> +        "operationFollowing": "operation following",
```suggestion
        "operationFollowing": "Operations following",
```

2023-06-29 02:12 UTC, frozenhelium commented on src/views/Account/AccountInfo/i18n.json
> +        "operationLastUpdated": "last updated",
Probably unused

2023-06-29 02:12 UTC, frozenhelium commented on src/views/Account/AccountInfo/i18n.json
> +        "currentlyFollowing": "currently following operations",
```suggestion
        "currentlyFollowing": "Currently following operations",
```

2023-07-06 13:08 UTC, frozenhelium requested changes
- Use translations
- Use generated typings

2023-07-20 04:49 UTC, barshathakuri approved these changes

2023-07-20 05:28 UTC, samshara approved these changes

2023-07-23 08:22 UTC, tnagorra commented on src/utils/common.ts
> +    return whitelistedDomains.some((domain) => domain === userMailDomain);
Let's add a FIXME

2023-07-23 08:22 UTC, tnagorra commented on src/views/AccountInformation/ChangePassword/index.tsx
> +            forceValue: nullValue,
```suggestion
            forceValue: undefinedValue,
```

2023-07-23 08:22 UTC, tnagorra commented on src/views/Register/index.tsx
> +            console.log('Server error::>>', formErrors);
Let's remove this console

2023-07-23 08:22 UTC, tnagorra commented on src/views/Register/index.tsx
> +        && isWhitelistedEmail(formValue.email.toLowerCase(), whitelistedDomains);
Let's update isWhitelistedEmail

2023-07-23 08:22 UTC, tnagorra commented on src/views/AccountInformation/index.tsx
> +                        />
Let's update this

2023-07-23 09:13 UTC, merged