Add legends in region risk watch
IFRCGo/go-web-app pull request #284
Opened 2023-11-06 11:33 UTC by barshathakuri

## Changes
- Add legends in region risk watch

## This PR doesn't introduce:
- [x] typos
- [x] conflict markers
- [x] unwanted comments
- [x] temporary files, auto-generated files or secret keys
- [x] `console.log` meant for debugging
- [x] codegen errors

2023-11-08 08:02 UTC, samshara approved these changes

2023-11-08 08:02 UTC, samshara commented on src/views/AccountMyFormsDref/ActiveDrefTable/i18n.json
> +        "activeDrefTitle": "Completed DREF Operations",
Is this the correct string translation?

2023-11-09 09:28 UTC, frozenhelium commented
@barshathakuri We should not merge back the `develop` branch to the current branch, we should do the `git rebase develop`

2023-11-09 09:34 UTC, frozenhelium requested changes

2023-11-09 09:34 UTC, frozenhelium commented on src/components/domain/RiskSeasonalMap/i18n.json
> +        "riskScoreOptionLabel": "INFORM Risk Score",
We are using both the `INFORM` and `WFP` for this one. So we should keep it as `Risk Score`

2023-11-09 09:34 UTC, frozenhelium commented on src/views/CountryRiskWatch/RiskBarChart/WildfireChart/index.tsx
> +                </text>
We should either create a separate component for this or implement it in the `ChartAxes` component

2023-11-20 04:35 UTC, closed without merging