Feature - country threew activities
IFRCGo/go-web-app pull request #309
Opened 2023-12-01 06:21 UTC by puranban

## Addresses:

- https://github.com/toggle-corp/ifrc-go-meta/issues/345
- https://github.com/toggle-corp/ifrc-go-meta/issues/346

## Changes

- Country page ongoing threeW activities 
  - Add  key figure card details section
  - Add activities map and list table
  - Add view all activities link 
  - Add csv export button

## This PR doesn't introduce:
- [x] typos
- [x] conflict markers
- [x] unwanted comments
- [x] temporary files, auto-generated files or secret keys
- [x] `console.log` meant for debugging
- [x] codegen errors

2023-12-04 05:10 UTC, frozenhelium requested changes

2023-12-04 05:10 UTC, frozenhelium commented on src/views/CountryOngoingActivities/index.tsx
> +    );
We can just forward `outletContext` from above
```jsx
const outletContext = useOutletContext<CountryOutletContext>();

...

<Outlet context=outletContext />
```

2023-12-04 05:10 UTC, frozenhelium commented on src/views/CountryOngoingActivitiesThreeWActivities/i18n.json
> +        "pageTitle": "Country Ongoing 3W Activities",
Let's remove unused string

2023-12-04 05:10 UTC, frozenhelium commented on src/views/CountryOngoingActivitiesThreeWActivities/index.tsx
> +        skip: (isNotDefined(countryId)),
```suggestion
        skip: isNotDefined(countryId),
```

2023-12-06 04:31 UTC, barshathakuri approved these changes

2023-12-06 06:22 UTC, samshara commented on src/views/CountryOngoingActivitiesThreeWActivities/Filters/index.tsx
> +    country: number[];
Let's remove this as it is not used here.

2023-12-06 06:22 UTC, samshara commented on src/views/CountryOngoingActivitiesThreeWActivities/index.tsx
> +            country: [],
Let's remove this unused filter

2023-12-06 08:04 UTC, samshara approved these changes

2023-12-06 10:12 UTC, frozenhelium requested changes

2023-12-06 10:12 UTC, frozenhelium commented on src/views/CountryOngoingActivities/index.tsx
> +import { useMemo } from 'react';
`useMemo` seems to be unused here

2023-12-06 10:12 UTC, frozenhelium commented on src/views/CountryOngoingActivitiesThreeWActivities/Filters/index.tsx
> +        <div className={_cs(styles.filters, className)}>
Let's remove the container `div` and just use Fragment (`<>`) it from the outer container's `useGridViewInFilter` prop

2023-12-06 10:12 UTC, frozenhelium commented on src/views/CountryOngoingActivitiesThreeWActivities/Filters/styles.module.css
> +}
We can use Container's filter prop for this styling

2023-12-14 13:44 UTC, frozenhelium approved these changes

2023-12-14 13:46 UTC, merged