Feature/move map tables
IFRCGo/go-web-app pull request #323
Opened 2023-12-05 10:39 UTC by barshathakuri

## Addresses:
- https://github.com/toggle-corp/ifrc-go-meta/issues/353
- https://github.com/toggle-corp/ifrc-go-meta/issues/352
- https://github.com/toggle-corp/ifrc-go-meta/issues/351

## Changes
- Add key figures from threeW activity to country pages > NS activity
- Add map from threeW activity to country pages > NS activity
- Add table from threeW activity to country pages > NS activity

## This PR doesn't introduce:
- [x] typos
- [x] conflict markers
- [x] unwanted comments
- [x] temporary files, auto-generated files or secret keys
- [x] `console.log` meant for debugging
- [x] codegen errors

2023-12-06 08:03 UTC, samshara approved these changes

2023-12-06 12:05 UTC, frozenhelium requested changes

2023-12-06 12:05 UTC, frozenhelium commented on src/views/CountryNsOverviewActivities/index.tsx
> +            saveAs(blob, `${countryResponse?.name}-data-export.csv`);
Let's add more context to the file name and also .
```suggestion
            saveAs(blob, `${countryResponse?.society_name}-international-works.csv`);
```

2023-12-06 12:05 UTC, frozenhelium commented on src/views/CountryNsOverviewActivities/index.tsx
> +            </div>
We should use existing page structure for this. Let's discuss on this.

2023-12-14 16:30 UTC, frozenhelium approved these changes

2023-12-14 16:30 UTC, merged