Add a context to store enums from server
IFRCGo/go-web-app pull request #35
Opened 2023-07-10 12:49 UTC by frozenhelium

2023-07-11 08:21 UTC, tnagorra requested changes

2023-07-11 08:21 UTC, tnagorra commented on src/views/PerWorkPlanForm/CustomComponentInput/index.tsx
> +                    // FIXME: add title attribute
We don't need this

2023-07-11 08:21 UTC, tnagorra commented on src/views/Search/EmergencyTable/index.tsx
> +            ),
We need to improve this.

2023-07-12 10:04 UTC, tnagorra requested changes

2023-07-12 10:04 UTC, tnagorra commented on src/views/Emergencies/EmergenciesTable/index.tsx
> +    const [page, setPage] = useState(0);
Let's confirm this is zero

2023-07-12 11:08 UTC, tnagorra commented on src/components/AppealsTable/index.tsx
> +                    filtered={!!(filterDisplacement && filterAppeal)}
```suggestion
                    filtered={!!(filterDisplacement || filterAppeal)}
```

2023-07-12 11:38 UTC, tnagorra commented on src/components/AppealsTable/index.tsx
> +                    filtered={!!(filterDisplacement && filterAppeal)}
Also let's use isDefined

2023-07-12 11:41 UTC, tnagorra commented
Using server `https://per-ifrc.dev.datafriendlyspace.org/` there are still 25 typeerrors.

The errors are not just on Register and Dref pages.
```
src/components/ActiveOperationMap/index.tsx:225:39 - error TS2352: Conversion of type 'string' to type '{ type: "Point"; coordinates: [number, number]; }' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
src/views/DrefApplicationForm/Operation/index.tsx:331:25 - error TS2322: Type 'string | undefined' is not assignable to type 'number | null | undefined'.
src/views/DrefApplicationForm/Operation/index.tsx:332:25 - error TS2322: Type '(...entries: EntriesAsList<{ title?: string | undefined; id?: number | undefined; status?: 0 | 1 | undefined; national_society?: number | undefined; ifrc?: string | undefined; translation_module_original_language?: string | undefined; ... 133 more ...; anticipatory_actions?: string | undefined; } & Pick<...>>) => void' is not assignable to type '(value: number | undefined, name: "disability_people_per", e?: FormEvent<HTMLInputElement> | undefined) => void'.
src/views/DrefApplicationForm/Operation/index.tsx:343:33 - error TS2322: Type 'string | undefined' is not assignable to type 'number | null | undefined'.
src/views/DrefApplicationForm/Operation/index.tsx:344:33 - error TS2322: Type '(...entries: EntriesAsList<{ title?: string | undefined; id?: number | undefined; status?: 0 | 1 | undefined; national_society?: number | undefined; ifrc?: string | undefined; translation_module_original_language?: string | undefined; ... 133 more ...; anticipatory_actions?: string | undefined; } & Pick<...>>) => void' is not assignable to type '(value: number | undefined, name: "people_per_urban", e?: FormEvent<HTMLInputElement> | undefined) => void'.
src/views/DrefApplicationForm/Operation/index.tsx:350:33 - error TS2322: Type 'string | undefined' is not assignable to type 'number | null | undefined'.
src/views/DrefApplicationForm/Operation/index.tsx:351:33 - error TS2322: Type '(...entries: EntriesAsList<{ title?: string | undefined; id?: number | undefined; status?: 0 | 1 | undefined; national_society?: number | undefined; ifrc?: string | undefined; translation_module_original_language?: string | undefined; ... 133 more ...; anticipatory_actions?: string | undefined; } & Pick<...>>) => void' is not assignable to type '(value: number | undefined, name: "people_per_local", e?: FormEvent<HTMLInputElement> | undefined) => void'.
src/views/Emergencies/Map/index.tsx:201:39 - error TS2352: Conversion of type 'string' to type '{ type: "Point"; coordinates: [number, number]; }' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
src/views/GlobalThreeW/Map/index.tsx:116:27 - error TS2352: Conversion of type 'string' to type '{ type: "Point"; coordinates: [number, number]; }' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
src/views/PerPrioritizationForm/index.tsx:260:21 - error TS2322: Type '{ id: number; area_details: { id: number; title: string; area_num?: number | undefined; }; area: number; component_responses?: { id: number; component: number; rating?: number | null | undefined; ... 4 more ...; climate_environmental_considerations?: string | ... 1 more ... | undefined; }[] | undefined; }[] | undefi...' is not assignable to type '({ id?: number | undefined; area_details?: ({ title?: string | undefined; id?: number | undefined; area_num?: number | undefined; } & Pick<{ id: number; title: string; area_num?: number | undefined; }, never>) | undefined; component_responses?: ({ ...; } & Pick<...>)[] | undefined; } & Pick<...>)[] | undefined'.
src/views/Register/index.tsx:51:41 - error TS2339: Property 'requestBody' does not exist on type '{ parameters: { query: { format?: "csv" | "json" | undefined; }; }; responses: { 200: unknown; }; }'.
src/views/Register/index.tsx:167:22 - error TS2345: Argument of type 'Record<string, unknown> & { [nonFieldError]: string; }' is not assignable to parameter of type 'SetErrorArg<LeafError | ArrayError<any> | ObjectError<any>>'.
src/views/Register/index.tsx:239:21 - error TS2322: Type 'LeafError | ArrayError<any> | ObjectError<any>' is not assignable to type 'ReactNode'.
src/views/Register/index.tsx:248:21 - error TS2322: Type 'LeafError | ArrayError<any> | ObjectError<any>' is not assignable to type 'ReactNode'.
src/views/Register/index.tsx:258:21 - error TS2322: Type 'LeafError | ArrayError<any> | ObjectError<any>' is not assignable to type 'ReactNode'.
src/views/Register/index.tsx:268:21 - error TS2322: Type 'LeafError | ArrayError<any> | ObjectError<any>' is not assignable to type 'ReactNode'.
src/views/Register/index.tsx:278:21 - error TS2322: Type 'LeafError | ArrayError<any> | ObjectError<any>' is not assignable to type 'ReactNode'.
src/views/Register/index.tsx:291:21 - error TS2322: Type 'LeafError | ArrayError<any> | ObjectError<any>' is not assignable to type 'ReactNode'.
src/views/Register/index.tsx:300:21 - error TS2322: Type 'LeafError | ArrayError<any> | ObjectError<any>' is not assignable to type 'ReactNode'.
src/views/Register/index.tsx:312:21 - error TS2322: Type 'LeafError | ArrayError<any> | ObjectError<any>' is not assignable to type 'ReactNode'.
src/views/Register/index.tsx:325:25 - error TS2322: Type 'LeafError | ArrayError<any> | ObjectError<any>' is not assignable to type 'ReactNode'.
src/views/Register/index.tsx:335:25 - error TS2322: Type 'LeafError | ArrayError<any> | ObjectError<any>' is not assignable to type 'ReactNode'.
src/views/Register/index.tsx:345:21 - error TS2322: Type 'LeafError | ArrayError<any> | ObjectError<any>' is not assignable to type 'ReactNode'.
src/views/Register/index.tsx:353:21 - error TS2322: Type 'LeafError | ArrayError<any> | ObjectError<any>' is not assignable to type 'ReactNode'.
src/views/Register/index.tsx:361:21 - error TS2322: Type 'LeafError | ArrayError<any> | ObjectError<any>' is not assignable to type 'ReactNode'.
```

2023-07-12 12:08 UTC, shreeyash07 approved these changes

2023-07-13 06:33 UTC, tnagorra requested changes

2023-07-13 06:33 UTC, tnagorra commented on src/views/Search/useColumns/index.tsx
> +    const columnMap = {
Let's use memo

2023-07-13 06:33 UTC, tnagorra commented on src/views/Search/index.tsx
> +            function getNormalizedScore(
```suggestion
            function getAverageScore(
```

2023-07-13 06:33 UTC, tnagorra commented on src/views/Search/ResultTable/index.tsx
> +            return newData;
```suggestion
    return mappings.data.slice(0, maxItems);
```

2023-07-13 08:08 UTC, frozenhelium commented
> @frozenhelium @thenav56
> 
> Using server `https://per-ifrc.dev.datafriendlyspace.org/` there are still 25 typeerrors.
> 
> The errors are not just on Register and Dref pages.
> 
> ```
> src/components/ActiveOperationMap/index.tsx:225:39 - error TS2352: Conversion of type 'string' to type '{ type: "Point"; coordinates: [number, number]; }' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
> src/views/DrefApplicationForm/Operation/index.tsx:331:25 - error TS2322: Type 'string | undefined' is not assignable to type 'number | null | undefined'.
> src/views/DrefApplicationForm/Operation/index.tsx:332:25 - error TS2322: Type '(...entries: EntriesAsList<{ title?: string | undefined; id?: number | undefined; status?: 0 | 1 | undefined; national_society?: number | undefined; ifrc?: string | undefined; translation_module_original_language?: string | undefined; ... 133 more ...; anticipatory_actions?: string | undefined; } & Pick<...>>) => void' is not assignable to type '(value: number | undefined, name: "disability_people_per", e?: FormEvent<HTMLInputElement> | undefined) => void'.
> src/views/DrefApplicationForm/Operation/index.tsx:343:33 - error TS2322: Type 'string | undefined' is not assignable to type 'number | null | undefined'.
> src/views/DrefApplicationForm/Operation/index.tsx:344:33 - error TS2322: Type '(...entries: EntriesAsList<{ title?: string | undefined; id?: number | undefined; status?: 0 | 1 | undefined; national_society?: number | undefined; ifrc?: string | undefined; translation_module_original_language?: string | undefined; ... 133 more ...; anticipatory_actions?: string | undefined; } & Pick<...>>) => void' is not assignable to type '(value: number | undefined, name: "people_per_urban", e?: FormEvent<HTMLInputElement> | undefined) => void'.
> src/views/DrefApplicationForm/Operation/index.tsx:350:33 - error TS2322: Type 'string | undefined' is not assignable to type 'number | null | undefined'.
> src/views/DrefApplicationForm/Operation/index.tsx:351:33 - error TS2322: Type '(...entries: EntriesAsList<{ title?: string | undefined; id?: number | undefined; status?: 0 | 1 | undefined; national_society?: number | undefined; ifrc?: string | undefined; translation_module_original_language?: string | undefined; ... 133 more ...; anticipatory_actions?: string | undefined; } & Pick<...>>) => void' is not assignable to type '(value: number | undefined, name: "people_per_local", e?: FormEvent<HTMLInputElement> | undefined) => void'.
> src/views/Emergencies/Map/index.tsx:201:39 - error TS2352: Conversion of type 'string' to type '{ type: "Point"; coordinates: [number, number]; }' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
> src/views/GlobalThreeW/Map/index.tsx:116:27 - error TS2352: Conversion of type 'string' to type '{ type: "Point"; coordinates: [number, number]; }' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
> src/views/PerPrioritizationForm/index.tsx:260:21 - error TS2322: Type '{ id: number; area_details: { id: number; title: string; area_num?: number | undefined; }; area: number; component_responses?: { id: number; component: number; rating?: number | null | undefined; ... 4 more ...; climate_environmental_considerations?: string | ... 1 more ... | undefined; }[] | undefined; }[] | undefi...' is not assignable to type '({ id?: number | undefined; area_details?: ({ title?: string | undefined; id?: number | undefined; area_num?: number | undefined; } & Pick<{ id: number; title: string; area_num?: number | undefined; }, never>) | undefined; component_responses?: ({ ...; } & Pick<...>)[] | undefined; } & Pick<...>)[] | undefined'.
> src/views/Register/index.tsx:51:41 - error TS2339: Property 'requestBody' does not exist on type '{ parameters: { query: { format?: "csv" | "json" | undefined; }; }; responses: { 200: unknown; }; }'.
> src/views/Register/index.tsx:167:22 - error TS2345: Argument of type 'Record<string, unknown> & { [nonFieldError]: string; }' is not assignable to parameter of type 'SetErrorArg<LeafError | ArrayError<any> | ObjectError<any>>'.
> src/views/Register/index.tsx:239:21 - error TS2322: Type 'LeafError | ArrayError<any> | ObjectError<any>' is not assignable to type 'ReactNode'.
> src/views/Register/index.tsx:248:21 - error TS2322: Type 'LeafError | ArrayError<any> | ObjectError<any>' is not assignable to type 'ReactNode'.
> src/views/Register/index.tsx:258:21 - error TS2322: Type 'LeafError | ArrayError<any> | ObjectError<any>' is not assignable to type 'ReactNode'.
> src/views/Register/index.tsx:268:21 - error TS2322: Type 'LeafError | ArrayError<any> | ObjectError<any>' is not assignable to type 'ReactNode'.
> src/views/Register/index.tsx:278:21 - error TS2322: Type 'LeafError | ArrayError<any> | ObjectError<any>' is not assignable to type 'ReactNode'.
> src/views/Register/index.tsx:291:21 - error TS2322: Type 'LeafError | ArrayError<any> | ObjectError<any>' is not assignable to type 'ReactNode'.
> src/views/Register/index.tsx:300:21 - error TS2322: Type 'LeafError | ArrayError<any> | ObjectError<any>' is not assignable to type 'ReactNode'.
> src/views/Register/index.tsx:312:21 - error TS2322: Type 'LeafError | ArrayError<any> | ObjectError<any>' is not assignable to type 'ReactNode'.
> src/views/Register/index.tsx:325:25 - error TS2322: Type 'LeafError | ArrayError<any> | ObjectError<any>' is not assignable to type 'ReactNode'.
> src/views/Register/index.tsx:335:25 - error TS2322: Type 'LeafError | ArrayError<any> | ObjectError<any>' is not assignable to type 'ReactNode'.
> src/views/Register/index.tsx:345:21 - error TS2322: Type 'LeafError | ArrayError<any> | ObjectError<any>' is not assignable to type 'ReactNode'.
> src/views/Register/index.tsx:353:21 - error TS2322: Type 'LeafError | ArrayError<any> | ObjectError<any>' is not assignable to type 'ReactNode'.
> src/views/Register/index.tsx:361:21 - error TS2322: Type 'LeafError | ArrayError<any> | ObjectError<any>' is not assignable to type 'ReactNode'.
> ```

Not anymore!

2023-07-13 09:06 UTC, tnagorra approved these changes

2023-07-13 09:06 UTC, merged