Remove form-field No. of people targeted from DREF Forms
IFRCGo/go-web-app pull request #425
Opened 2024-01-05 10:06 UTC by UjjwalDhakal7

## Addresses:
- (https://github.com/toggle-corp/ifrc-go-meta/issues/502)

## Changes
- Remove form-field 'No. of people targeted' from DREF Forms
- Remove schema 

## This PR doesn't introduce:
- [x] typos
- [x] conflict markers
- [x] unwanted comments
- [x] temporary files, auto-generated files or secret keys
- [x] `console.log` meant for debugging
- [x] codegen errors

2024-01-08 05:21 UTC, shreeyash07 requested changes

2024-01-08 05:21 UTC, shreeyash07 commented on src/views/DrefApplicationForm/EventDetail/index.tsx
> -                                {strings.drefFormPeopleTargeted}
Remove it from strings files too

2024-01-09 08:26 UTC, barshathakuri commented
Base branch should be `project/dref-super-ticket-fixes` @UjjwalDhakal7 .

2024-01-10 10:36 UTC, barshathakuri approved these changes

2024-01-16 11:12 UTC, samshara approved these changes

2024-01-16 11:14 UTC, samshara approved these changes

2024-01-16 11:17 UTC, merged