Fix/dref forms
IFRCGo/go-web-app pull request #442
Opened 2024-01-10 04:38 UTC by utsukta1

## Addresses:
- https://github.com/toggle-corp/ifrc-go-meta/issues/507
- https://github.com/toggle-corp/ifrc-go-meta/issues/508

## Changes
- Move the fields to the Planned Intervention section of Operation page for each DREF form,remove DREF Allocation from fields
- Pop out the supporting documents in a new tab rather than opening them on the same tab in  all DFREF export

## This PR doesn't introduce:
- [x] typos
- [x] conflict markers
- [x] unwanted comments
- [x] temporary files, auto-generated files or secret keys
- [x] `console.log` meant for debugging
- [x] codegen errors

2024-01-10 10:32 UTC, barshathakuri commented on test.txt
> +no changes added to commit (use "git add" and/or "git commit -a")
Please remove unused file.

2024-01-12 05:12 UTC, shreeyash07 approved these changes

2024-01-16 04:40 UTC, shreeyash07 requested changes

2024-01-16 04:40 UTC, shreeyash07 commented on src/views/EmergencySurge/RapidResponsePerosnnelTable/index.tsx
> +                    if (item.country_from?.id) {
use isDefined or isNotDefined from fujs

2024-01-16 05:39 UTC, shreeyash07 approved these changes

2024-01-16 10:12 UTC, samshara approved these changes

2024-01-16 10:22 UTC, merged