Change ppp iframe link,display error message in surge pages
IFRCGo/go-web-app pull request #445
Opened 2024-01-10 06:45 UTC by utsukta1

## Addresses:
- https://github.com/IFRCGo/go-web-app/issues/431
- https://github.com/IFRCGo/go-web-app/issues/429

## Changes
- On three-w/projects the PPP iframe link changed in Global Three W
- Add error message in Rapid response Personnel table

## This PR doesn't introduce:
- [x] typos
- [x] conflict markers
- [x] unwanted comments
- [x] temporary files, auto-generated files or secret keys
- [x] `console.log` meant for debugging
- [x] codegen errors

2024-01-12 05:02 UTC, shreeyash07 approved these changes

2024-01-16 05:31 UTC, shreeyash07 requested changes

2024-01-16 05:31 UTC, shreeyash07 commented on src/views/EmergencySurge/RapidResponsePerosnnelTable/index.tsx
> +                    if (item.country_from?.id) {
use isDefined or isNotDefined from fujs

2024-01-16 10:22 UTC, samshara commented on src/views/AllDeployedPersonnel/index.tsx
> +                    }
Let's add a NOTE here.
// NOTE: we don't have the correct mapping for region

2024-01-16 10:22 UTC, samshara commented on src/views/EmergencySurge/RapidResponsePersonnelTable/i18n.json
> +        "emergencySurgePartyNotFound": "sorry, this party has no one matching country to be shown"
Let's remove this

2024-01-16 10:22 UTC, samshara commented on src/views/EmergencySurge/RapidResponsePersonnelTable/index.tsx
> +                        };
Let's add a note

2024-01-16 10:22 UTC, samshara commented on src/views/EmergencySurge/RapidResponsePersonnelTable/index.tsx
> +                        };
Let's use a constant to denote region type.
For example 
export const TYPE_IMMINENT = 0 satisfies TypeOfDrefEnum;

2024-01-16 10:29 UTC, closed without merging