Added  missing alert type  in the event details for GDACS
IFRCGo/go-web-app pull request #455
Opened 2024-01-11 08:39 UTC by roshni73

## Addresses:
-https://github.com/toggle-corp/ifrc-go-meta/issues/517

## Changes
- Added  missing alert type  in the event details for GDACS

## This PR doesn't introduce:
- [x] typos
- [x] conflict markers
- [x] unwanted comments
- [x] temporary files, auto-generated files or secret keys
- [x] `console.log` meant for debugging
- [x] codegen errors

2024-01-12 05:00 UTC, shreeyash07 commented on src/components/Alert/i18n.json
> +        "CopyErrorDetails": "Copy error details",
Revert these changes

2024-01-12 05:01 UTC, shreeyash07 requested changes

2024-01-12 05:01 UTC, shreeyash07 commented on src/components/Alert/index.tsx
> +                        {/* FIXME: there is string in json file */}
Remove this too

2024-01-12 05:01 UTC, shreeyash07 commented on src/components/Alert/i18n.json
> +        "CopyErrorDetails": "Copy error details",
Revert these changes

2024-01-12 05:37 UTC, shreeyash07 approved these changes

2024-01-16 09:30 UTC, samshara requested changes

2024-01-16 09:30 UTC, samshara commented on src/components/domain/RiskImminentEvents/Gdacs/EventDetails/index.tsx
> +    alert_sent?: boolean;
Let's remove this since it's not used

2024-01-16 09:30 UTC, samshara commented on src/components/domain/RiskImminentEvents/index.tsx
> +    alertType?:string;
Let's remove this as well

2024-01-16 09:30 UTC, samshara commented on src/views/Emergencies/index.tsx
> +            start_date: encodeDate(thirtyDaysAgo),
Why was it changed?

2024-01-16 09:30 UTC, samshara commented on src/views/RegionRiskWatchImminent/index.tsx
>  import styles from './styles.module.css';
There should be a empty line between absolute imports and relative imports

2024-01-16 09:30 UTC, samshara commented on src/views/RegionRiskWatchImminent/index.tsx
> -
Let's keep an empty line between the function and it's return value

2024-01-17 06:03 UTC, samshara commented
Closing this as this is superseeded by https://github.com/IFRCGo/go-web-app/pull/460

2024-01-17 06:03 UTC, closed without merging