DREF super ticket fixes
IFRCGo/go-web-app pull request #477
Opened 2024-01-18 05:22 UTC by samshara

## Addresses:
- https://github.com/IFRCGo/go-web-app/issues/379

## This PR doesn't introduce:
- [x] typos
- [x] conflict markers
- [x] unwanted comments
- [x] temporary files, auto-generated files or secret keys
- [x] `console.log` meant for debugging
- [x] codegen errors

2024-01-18 06:31 UTC, UjjwalDhakal7 approved these changes

2024-01-18 07:51 UTC, roshni73 approved these changes

2024-01-18 07:51 UTC, utsukta1 approved these changes

2024-01-18 07:51 UTC, fereeca approved these changes

2024-01-18 08:03 UTC, roshni73 approved these changes

2024-01-19 10:22 UTC, barshathakuri requested changes

2024-01-19 10:22 UTC, barshathakuri commented on src/views/AllDeployedPersonnel/index.tsx
> +import { isDefined } from '@togglecorp/fujs';
Please follow the coding structure.

2024-01-19 10:22 UTC, barshathakuri commented on src/views/AllDeployedPersonnel/index.tsx
> +                            to: undefined,
Why do we comparing `record_type` to 3. Use `enum`

2024-01-19 10:22 UTC, barshathakuri commented on src/views/DrefApplicationExport/styles.module.css
> +
Please Remove the extra line.

2024-01-19 10:22 UTC, barshathakuri commented on src/views/DrefApplicationForm/schema.ts
>                      };
Please revert the change `event_text: { validations: [max500CharCondition] },` should be inside the val?.type_of_dref === TYPE_IMMINENT condition.

2024-01-19 10:22 UTC, barshathakuri commented on src/views/EmergencySurge/RapidResponsePersonnelTable/index.tsx
> +                        };
Use `enums` for comparisons.

2024-01-19 10:22 UTC, barshathakuri commented on src/views/EmergencySurge/RapidResponsePersonnelTable/styles.module.css
Why did we rename this file?

2024-01-19 10:22 UTC, barshathakuri commented on src/views/EmergencySurge/RapidResponsePersonnelTable/i18n.json
Why did we rename this file?

2024-01-22 08:55 UTC, frozenhelium approved these changes

2024-01-22 09:01 UTC, frozenhelium requested changes
We should squash the commits to avoid conflicts with the country pages @samshara

2024-01-22 11:57 UTC, frozenhelium approved these changes

2024-01-22 12:01 UTC, barshathakuri approved these changes

2024-01-22 12:01 UTC, merged