Add imminent event map
IFRCGo/go-web-app pull request #48
Opened 2023-07-25 18:02 UTC by frozenhelium

2023-07-31 17:01 UTC, tnagorra requested changes

2023-07-31 17:01 UTC, tnagorra commented on src/views/RegionRiskWatch/index.tsx
> +    const bbox = regionResponse ? getBbox(regionResponse.bbox) : undefined;
Let's memoize this

2023-07-31 17:01 UTC, tnagorra commented on src/views/CountryRiskWatch/index.tsx
> +    const bbox = countryResponse ? getBbox(countryResponse.bbox) : undefined;
Let's memoize this

2023-07-31 17:01 UTC, tnagorra commented on src/utils/risk.ts
> +    }
We need a try catch here

2023-07-31 17:01 UTC, tnagorra commented on src/utils/risk.ts
> +export function isValidFeature(
The check does not confirm that the feature is GeoJSON.Feature

2023-07-31 17:01 UTC, tnagorra commented on src/utils/risk.ts
> +export function isValidPointFeature(
The check does not confirm that the feature is GeoJSON.Feature<GeoJSON.Point>

2023-07-31 17:01 UTC, tnagorra commented on src/components/PdcImminentEvents/EventDetails/index.tsx
> +    };
Lets add a FIXME. Why do we need to cast this?
Also, we should not cast nullable item as non-nullable.

2023-07-31 17:01 UTC, tnagorra commented on src/components/PdcImminentEvents/index.tsx
> +            || (variant === 'country' && isNotDefined(props.iso3)),
Why not destructuring regionId and iso3 here?

2023-07-31 17:01 UTC, tnagorra commented on src/components/PdcImminentEvents/index.tsx
> +                ?.filter(isValidPointFeature);
Let's add a FIXME here. We should not require casting to unknown for a response from server.

2023-07-31 17:01 UTC, tnagorra commented on src/components/PdcImminentEvents/index.tsx
> +                    geoJson as GeoJSON.FeatureCollection<GeoJSON.Geometry>,
Let's not cast geoJson here. Let's just give this type to the variable geoJson on line 86

2023-07-31 17:01 UTC, tnagorra commented on src/components/PdcImminentEvents/index.tsx
> +            footprintCallbackRef.current = callback;
We can pass this function directly to getFootprint as context. We can avoid the ref.

2023-07-31 17:01 UTC, tnagorra commented on src/components/RiskImminentEventMap/index.tsx
> +    };
Let's memoize this variable

2023-07-31 17:01 UTC, tnagorra commented on src/components/RiskImminentEventMap/index.tsx
> +            ),
We should not pass elements to rendererParams

2023-07-31 17:01 UTC, tnagorra commented on src/components/RiskImminentEventMap/index.tsx
> +                                        'circle-radius': 4,
Let's move the options outside the render.
This will call mapbox functions on each render.

2023-07-31 17:01 UTC, tnagorra commented on src/components/RiskImminentEventMap/index.tsx
> +                    </Button>
Let's add translation or a FIXME note

2023-08-01 03:29 UTC, frozenhelium commented on src/components/PdcImminentEvents/index.tsx
> +            || (variant === 'country' && isNotDefined(props.iso3)),
Conditional types

2023-08-01 05:18 UTC, tnagorra commented on src/components/PdcImminentEvents/EventListItem/index.tsx
> +                    variant="tertiary"
Let's add a title on icon button

2023-08-01 05:32 UTC, tnagorra approved these changes

2023-08-01 05:32 UTC, merged