Added supported by organization type to listbox with options,allowed …
IFRCGo/go-web-app pull request #483
Opened 2024-01-19 11:12 UTC by roshni73

## Addresses:
-  https://github.com/IFRCGo/go-web-app/issues/451

## Changes
- Added supported by organization type to listbox with options,
- allowed the selection of a National Society when Supported by organization type is National Society.

## This PR doesn't introduce:
- [x] typos
- [x] conflict markers
- [x] unwanted comments
- [x] temporary files, auto-generated files or secret keys
- [x] `console.log` meant for debugging
- [x] codegen errors

2024-01-25 06:32 UTC, barshathakuri requested changes

2024-01-25 06:32 UTC, barshathakuri commented on src/views/PerWorkPlanForm/PrioritizedActionInput/index.tsx
> +            {value?.supported_by_organization_type === 3 && (
Please compare with the enum. Let me know if you have any confusion.

2024-01-30 06:27 UTC, samshara approved these changes

2024-01-30 06:32 UTC, barshathakuri commented on src/views/PerWorkPlanForm/PrioritizedActionInput/index.tsx
> +    const { per_supported_by_organization_type } = useGlobalEnums();
```suggestion
    const { per_workplanstatus, per_supported_by_organization_type } = useGlobalEnums();
```

2024-01-30 06:33 UTC, barshathakuri commented on src/views/PerWorkPlanForm/PrioritizedActionInput/index.tsx
> +
Remove extra line

2024-01-30 06:37 UTC, barshathakuri requested changes

2024-01-30 06:37 UTC, barshathakuri commented on src/views/PerWorkPlanForm/PrioritizedActionInput/index.tsx
> +    const { per_supported_by_organization_type } = useGlobalEnums();
```suggestion
    const { per_workplanstatus, per_supported_by_organization_type } = useGlobalEnums();
```

2024-01-30 06:37 UTC, barshathakuri commented on src/views/PerWorkPlanForm/PrioritizedActionInput/index.tsx
> +
Remove extra line

2024-01-30 09:30 UTC, barshathakuri approved these changes

2024-01-30 09:30 UTC, merged