Change start date from immediately to closed date of closed alert in surge
IFRCGo/go-web-app pull request #516
Opened 2024-01-24 10:18 UTC by utsukta1

## Addresses:
- https://github.com/IFRCGo/go-web-app/issues/512

## Changes
- When Alerts are "Closed" , changed the start date from "Immediately" to the day the alert was closed 

## This PR doesn't introduce:
- [x] typos
- [x] conflict markers
- [x] unwanted comments
- [x] temporary files, auto-generated files or secret keys
- [x] `console.log` meant for debugging
- [x] codegen errors

2024-01-25 06:26 UTC, barshathakuri requested changes

2024-01-25 06:26 UTC, barshathakuri commented on src/views/AllSurgeAlerts/index.tsx
> -            strings.surgeAlertImmediately,
Please remove `strings.surgeAlertImmediately,` from the i18 file as well.

2024-01-29 06:10 UTC, barshathakuri approved these changes

2024-01-29 10:57 UTC, samshara approved these changes

2024-01-29 11:05 UTC, merged