Add details to 3W page
IFRCGo/go-web-app pull request #52
Opened 2023-07-27 11:14 UTC by barshathakuri

## This PR doesn't introduce:
- [ ] typos
- [ ] conflict markers
- [ ] unwanted comments
- [ ] temporary files, auto-generated files or secret keys
- [ ] `console.log` meant for debugging
- [ ] codegen errors

2023-08-02 09:23 UTC, samshara approved these changes

2023-08-02 09:23 UTC, samshara commented on src/App/routes.tsx
> +        title: 'ThreeW Detail',
```suggestion
        title: 'ThreeW Details',
```

2023-08-07 16:40 UTC, tnagorra requested changes, later dismissed

2023-08-07 16:40 UTC, tnagorra commented on src/views/ThreeWDetails/i18n.json
> +    "namespace": "surge",
```suggestion
    "namespace": "threeWDetails",
```

2023-08-07 16:40 UTC, tnagorra commented on src/views/ThreeWDetails/index.tsx
> +                                    `${projectResponse?.reporting_ns_contact_name ?? ''}
We do not need fallback for this variable

2023-08-07 16:40 UTC, tnagorra commented on src/views/ThreeWDetails/index.tsx
> +                                    ${projectResponse?.reporting_ns_contact_role ?? ''}`
Let's filter undefined string and join by a `,`

2023-08-15 17:39 UTC, tnagorra requested changes

2023-08-15 17:39 UTC, tnagorra commented on src/views/ThreeWDetails/index.tsx
> +        },
Let's check if the threeWId is defined before we cast to number

2023-08-15 17:39 UTC, tnagorra commented on src/views/ThreeWDetails/index.tsx
> +                                    <>{projectResponse?.modified_by_detail}</>
Let's remove the fragment here

2023-08-15 17:39 UTC, tnagorra commented on src/views/ThreeWDetails/index.tsx
> +                                    ? `${projectResponse?.project_districts_detail?.map((district) => district?.name).join(', ')}`
Why reason to use string template here?

2023-08-22 12:50 UTC, AdityaKhatri requested changes

2023-08-22 12:50 UTC, AdityaKhatri commented on src/App/routes.tsx
> +const threeWProjectDetail = customWrapRoute({
Support this on listing page as well

2023-08-22 12:50 UTC, AdityaKhatri commented on src/views/ThreeWProjectDetail/index.tsx
> +                    withoutLabelColon
modified_by_detail is null sometimes.
Don't display this is its empty.

2023-08-22 12:50 UTC, AdityaKhatri commented on src/views/ThreeWProjectDetail/index.tsx
> +                                            ) : undefined}
write this outside for simplicity and less nesting

2023-08-22 12:50 UTC, AdityaKhatri commented on src/views/ThreeWProjectDetail/index.tsx
> +                                        : null}
write this outside for simplicity and less nesting

2023-08-22 12:50 UTC, AdityaKhatri commented on src/views/ThreeWProjectDetail/index.tsx
> +                                    <div className={styles.yearList}>
UI is not consistent with the previous one.
![image](https://github.com/IFRCGo/go-web-app/assets/7893887/7a618fab-7ed5-44ec-acc5-a86cd4c9f771)

2023-08-23 11:20 UTC, barshathakuri commented on src/App/routes.tsx
> +const threeWProjectDetail = customWrapRoute({
Please explain

2023-08-23 13:21 UTC, AdityaKhatri commented on src/views/ThreeWProjectDetail/index.tsx
> +                            </div>
Use list

2023-08-25 11:47 UTC, merged