Feature/per upload document
IFRCGo/go-web-app pull request #545
Opened 2024-01-30 10:49 UTC by fereeca

## Addresses:
- https://github.com/IFRCGo/go-web-app/issues/450

## Changes
- Created UI to upload, download and delete documents under country preparedness
- Added container to display the uploaded documents
- Added disclaimer indicating the document limits

## This PR doesn't introduce:
- [x] typos
- [x] conflict markers
- [x] unwanted comments
- [x] temporary files, auto-generated files or secret keys
- [x] `console.log` meant for debugging
- [x] codegen errors

2024-01-31 05:19 UTC, shreeyash07 approved these changes

2024-01-31 06:31 UTC, barshathakuri requested changes

2024-01-31 06:31 UTC, barshathakuri commented on src/views/CountryPreparedness/index.tsx
> +                            Note: You can only upload upto 10 documents.
Please use strings translation

2024-01-31 10:07 UTC, shreeyash07 approved these changes

2024-02-27 08:26 UTC, barshathakuri approved these changes

2024-02-29 11:45 UTC, merged