Make PER overview partially editable
IFRCGo/go-web-app pull request #58
Opened 2023-08-02 06:40 UTC by frozenhelium

2023-08-04 11:17 UTC, samshara commented on src/views/CountryPreparedness/index.tsx
> +                    Chart not available
Shouldn't this come from translations

2023-08-04 11:17 UTC, samshara commented on src/views/CountryPreparedness/index.tsx
> +                    />
Let's use defined functions

2023-08-07 17:09 UTC, tnagorra requested changes

2023-08-07 17:09 UTC, tnagorra commented on src/components/ChartAxes/index.tsx
> +    showBoundRects?: boolean,
```suggestion
    boundRectsShown?: boolean,
```

2023-08-07 17:09 UTC, tnagorra commented on src/components/ChartAxisY/index.tsx
> +    const yAxisTickHeight = Math.max(
Let's add NOTE why dividing by zero is not problematic here.

2023-08-07 17:09 UTC, tnagorra commented on src/views/CountryPreparedness/index.tsx
> +    const prevAssessmentRatings = latestPerResponse?.results?.[0]?.assessment_ratings;
Why do we take first element? Let's add a NOTE

2023-08-07 17:09 UTC, tnagorra commented on src/views/CountryPreparedness/index.tsx
> +                    label: `${formAnswerMap[answerList[0].answer]} ${answerList.length}`,
Are we sure that the mapping will not return an undefined value

2023-08-07 17:09 UTC, tnagorra commented on src/views/CountryPreparedness/index.tsx
> +                            Contact PER Team
Let's translate

2023-08-07 17:09 UTC, tnagorra commented on src/views/CountryPreparedness/index.tsx
> +                                        `${component.rating?.value} - ${component.rating?.title}`
Let's make sure we don't pass undefined in string literals

2023-08-07 17:09 UTC, tnagorra commented on src/views/CountryPreparedness/index.tsx
> +                                    ) : '0 - Not Reviewed'}
Let's translate

2023-08-07 17:09 UTC, tnagorra commented on src/views/CountryPreparedness/PreviousAssessmentChart/index.tsx
> +                                {`Assessment: ${point.xValue}, Rating: ${point.yValue ?? '-'}`}
Let's translate

2023-08-07 17:09 UTC, tnagorra commented on src/views/CountryPreparedness/PreviousAssessmentChart/index.tsx
> +                        d={getDiscretePathDataList(chartData.points)?.[0]}
why only use first elem?

2023-08-07 17:09 UTC, tnagorra commented on src/utils/per.ts
> +export const PER_PHASE_ACTION = 5;
Let;s use `satisfies`

2023-08-07 17:09 UTC, tnagorra commented on src/utils/chart.ts
> +export function getBounds(numList: UnsafeNumberList, zeroMin = false) {
Let's remove zeroMin from this function

2023-08-08 11:50 UTC, merged