WIP
IFRCGo/go-web-app pull request #71
Opened 2023-08-09 10:50 UTC by tnagorra

## This PR doesn't introduce:
- [ ] typos
- [ ] conflict markers
- [ ] unwanted comments
- [ ] temporary files, auto-generated files or secret keys
- [ ] `console.log` meant for debugging
- [ ] codegen errors

2023-08-14 08:52 UTC, frozenhelium requested changes

2023-08-14 08:52 UTC, frozenhelium commented on src/components/RadioInput/Radio/styles.module.css
> +            color: var(--go-ui-color-gray-70);
```suggestion
            color: var(--go-ui-color-text-light);
```

2023-08-14 08:52 UTC, frozenhelium commented on src/views/FieldReportForm/ContextFields/styles.module.css
> +}
Let's not leave empty stylings

2023-08-14 08:52 UTC, frozenhelium commented on src/views/FieldReportForm/ResponseFields/styles.module.css
> +}
1. Let's not leave it empty
2. 
```suggestion
.response-fields {
}
```

2023-08-14 08:52 UTC, frozenhelium commented on src/views/FieldReportForm/RiskAnalysisFields/styles.module.css
> +}
Let not keep empty styles

2023-08-14 10:53 UTC, tnagorra commented on src/views/FieldReportForm/RiskAnalysisFields/styles.module.css
> +}
Styling is a WIP

2023-08-14 10:53 UTC, tnagorra commented on src/views/FieldReportForm/ResponseFields/styles.module.css
> +}
Styling is a WIP

2023-08-14 10:53 UTC, tnagorra commented on src/views/FieldReportForm/ContextFields/styles.module.css
> +}
Styling is a WIP

2023-08-14 10:53 UTC, tnagorra commented on src/components/RadioInput/Radio/styles.module.css
> +            color: var(--go-ui-color-gray-70);
Yes sir!

2023-08-15 14:09 UTC, frozenhelium approved these changes

2023-08-15 16:05 UTC, merged