New fields in Dref application form when type is imminent
IFRCGo/go-web-app pull request #737
Opened 2024-03-05 08:00 UTC by shreeyash07

## Addresses:
- #698 

## Changes
- Added new fields in Dref application form when dref type is imminent

## This PR doesn't introduce:
- [x] typos
- [x] conflict markers
- [x] unwanted comments
- [x] temporary files, auto-generated files or secret keys
- [x] `console.log` meant for debugging
- [x] codegen errors

2024-03-15 04:43 UTC, samshara commented on app/src/components/domain/DrefMultiFileInput/index.tsx
Any reason why we are creating a thing wrapper over `GoMultiFileInput` ?

2024-03-15 04:43 UTC, samshara commented on app/src/views/DrefApplicationForm/Actions/index.tsx
> +                        : null
we could use && instead of using ternary operator

2024-03-15 04:43 UTC, samshara commented on app/src/views/DrefApplicationForm/Operation/index.tsx
> +                            : null
we could use && here as well

2024-03-15 09:07 UTC, shreeyash07 commented on app/src/components/domain/DrefMultiFileInput/index.tsx
Only reason is to handle the onChange and inputValue like other Dref multi file input module

2024-03-19 05:54 UTC, frozenhelium commented on app/src/views/DrefApplicationForm/Actions/NeedInput/i18n.json
> +        "drefApplicationLabel": "Current needs of population at risk ",
```suggestion
        "drefApplicationLabel": "Current needs of population at risk",
```

2024-03-20 05:42 UTC, frozenhelium requested changes

2024-03-20 05:42 UTC, frozenhelium commented on app/src/views/DrefApplicationForm/Actions/NeedInput/i18n.json
> +        "drefApplicationLabel": "Current needs of population at risk ",
Lets also rename the key to more appropriate variable: maybe `currentNeedsLabel` or something similar

2024-03-20 05:42 UTC, frozenhelium commented on app/src/views/DrefApplicationForm/Actions/NeedInput/index.tsx
> +                className={styles.descriptionInput}
Let's rename the `className` to something common if we're to re-use the style.

2024-03-20 05:49 UTC, frozenhelium commented
Please update the PR description to reflect what changes have been made

2024-03-20 10:05 UTC, frozenhelium approved these changes

2024-03-20 10:06 UTC, merged