Add details for flash update
IFRCGo/go-web-app pull request #82
Opened 2023-08-14 11:18 UTC by barshathakuri

## Addresses:
- XXX

## Depends on:
- XXX

## Changes
- Detailed list or prose of changes
- Breaking changes
- Changes to configurations

## This PR doesn't introduce:
- [ ] typos
- [ ] conflict markers
- [ ] unwanted comments
- [ ] temporary files, auto-generated files or secret keys
- [ ] `console.log` meant for debugging
- [ ] codegen errors

2023-08-15 11:12 UTC, samshara approved these changes

2023-08-15 11:12 UTC, samshara commented on src/views/FlashUpdateDetails/index.tsx
> +                        )}
we should join the strings with `,`

2023-08-15 11:12 UTC, samshara commented on src/views/FlashUpdateDetails/index.tsx
> +                                        alt=""
can't we use approprite `alt`

2023-08-15 17:44 UTC, tnagorra requested changes

2023-08-15 17:44 UTC, tnagorra commented on src/views/FlashUpdateDetails/index.tsx
> +        },
Let's check if flashUpdateId defined before we cast to number

2023-08-15 17:44 UTC, tnagorra commented on src/views/FlashUpdateDetails/index.tsx
> +                    </Button>
```suggestion
                    <Button
                        name="export"
                    >
                        {strings.flashUpdateExport}
                    </Button>
                    <Button
                        name="share"
                    >
                        {strings.flashUpdateShare}
                    </Button>
```

2023-08-15 17:44 UTC, tnagorra commented on src/views/FlashUpdateDetails/index.tsx
> +                    >
Let's add key prop

2023-08-15 17:44 UTC, tnagorra commented on src/views/FlashUpdateDetails/index.tsx
> +                                        alt=""
Let's pass appropriate alt text

2023-08-20 04:54 UTC, tnagorra requested changes

2023-08-20 04:54 UTC, tnagorra commented on src/views/FlashUpdateDetails/index.tsx
> +    );
Let's memoize these

2023-08-22 12:55 UTC, AdityaKhatri requested changes
Fix links in flash update.
Add navigational links to flash update view and edit pages in flash update list page.

Flash update listing page's url is `flash-updates/all` and invidual is `flash-update/{id}` we need to make this consistent as well.

2023-08-22 12:55 UTC, AdityaKhatri commented on src/views/FlashUpdateDetails/index.tsx
> +            (at) => at?.actions?.length !== 0 || at.summary,
```suggestion
            (action) => action?.actions?.length !== 0 || action.summary,
```

2023-08-22 12:55 UTC, AdityaKhatri commented on src/views/FlashUpdateDetails/index.tsx
> +                                    )}
Fix UI inconsistencies

2023-08-23 13:00 UTC, AdityaKhatri approved these changes

2023-08-23 13:01 UTC, merged