Preparedness tab in region
IFRCGo/go-web-app pull request #88
Opened 2023-08-17 11:01 UTC by shreeyash07

## Addresses:
- [Preparedness- region](https://github.com/orgs/toggle-corp/projects/8/views/21?pane=issue&itemId=29916769)

## Changes
- Add HtmlOutput component for snippet response

## This PR doesn't introduce:
- [x] typos
- [x] conflict markers
- [x] unwanted comments
- [x] temporary files, auto-generated files or secret keys
- [x] `console.log` meant for debugging
- [x] codegen errors

2023-08-17 11:08 UTC, frozenhelium requested changes

2023-08-17 11:08 UTC, frozenhelium commented on src/views/Region/index.tsx
> +                ) : null}
- Don't have to optional chain `regionResponse` when it's already checked
- Also check if `preparedness_snippets` is defined before accessing the length
- Even better if a variable is defined for this (e.g. `hasPreparedSnippets`)
- ? : can be replaced by &&
```suggestion
                {(regionResponse && regionResponse.preparedness_snippets && preparedness_snippets.length > 0) && (
                    <NavigationTab
                        to={generatePath(
                            regionPreparednessRoute.absolutePath,
                            { regionId },
                        )}
                    >
                        {strings.regionPreparednessTab}
                    </NavigationTab>
                ) }
```

2023-08-17 11:08 UTC, frozenhelium commented on src/views/RegionPreparedness/index.tsx
> +                )
Missing trailing comma

2023-08-18 13:36 UTC, tnagorra requested changes

2023-08-18 13:36 UTC, tnagorra commented on src/utils/outletContext.ts
> +type RegionKeyFigureResponse = paths['/api/v2/region_key_figure/']['get']['responses']['200']['content']['application/json'];
Let's use helper GoApiResponse from restRequest

2023-08-18 13:36 UTC, tnagorra commented on src/views/Region/index.tsx
> +        : strings.regionAdditionalInfoTab;
We can just use `??` or `||` to provide default value

2023-08-18 13:36 UTC, tnagorra commented on src/views/RegionPreparedness/index.tsx
> +            )}
Let's also handle case when the preparedness_snippes is empty.

@AdityaKhatri @frozenhelium Should we use List component instead? Or just use message component?

2023-08-18 13:36 UTC, tnagorra commented on src/views/RegionAdditionalInfo/index.tsx
> +            {hasRegionResponse && (
Should we show a message if we do not have data?

cc: @frozenhelium @AdityaKhatri

2023-08-21 10:22 UTC, tnagorra requested changes

2023-08-21 10:22 UTC, tnagorra commented on src/views/Region/index.tsx
> +        skip: !regionId,
```suggestion
        skip: isNotDefined(regionId),
```

2023-08-21 10:22 UTC, tnagorra commented on src/views/Region/index.tsx
> +    const additionalInfoTabName = regionResponse?.additional_tab_name
```suggestion
    const additionalInfoTabName = !!regionResponse?.additional_tab_name
```

2023-08-21 10:22 UTC, tnagorra commented on src/views/Region/index.tsx
> +        regionResponse?.additional_tab_name
```suggestion
        !!regionResponse?.additional_tab_name
```

2023-08-21 10:22 UTC, tnagorra commented on src/views/RegionPreparedness/index.tsx
> +import type { RegionOutletContext, RegionResponse } from '#utils/outletContext';
```suggestion
import { type RegionOutletContext, type RegionResponse } from '#utils/outletContext';
```

2023-08-21 10:22 UTC, tnagorra commented on src/views/RegionAdditionalInfo/index.tsx
> +            {hasKeyFigure && (
Let's handle case when hasKeyFigure and hasRegionResponse is false.

2023-08-21 10:22 UTC, tnagorra commented on src/views/RegionAdditionalInfo/index.tsx
> +        && regionResponse?.snippets;
Let's also check length of the snippet

2023-08-21 10:22 UTC, tnagorra commented on src/views/RegionAdditionalInfo/index.tsx
> +            key={id}
We don't need key here

2023-08-21 10:22 UTC, tnagorra commented on src/views/RegionAdditionalInfo/index.tsx
> +import type { RegionOutletContext, RegionKeyFigureResponse, RegionResponse } from '#utils/outletContext';
Let's change how type are imported.

2023-08-21 16:40 UTC, tnagorra requested changes

2023-08-21 16:40 UTC, tnagorra commented on src/views/RegionPreparedness/i18n.json
> +        "NoDataMessage": "No Data to Display"
```suggestion
        "noDataMessage": "No data to display"
```

2023-08-21 16:40 UTC, tnagorra commented on src/views/RegionPreparedness/index.tsx
> +        && (regionResponse?.snippets.length > 0));
Why are we reading snippets when we are iterating over preparedness_snippets?

2023-08-21 16:40 UTC, tnagorra commented on src/views/RegionPreparedness/index.tsx
> +                />
This should be handled by the List component

2023-08-21 16:40 UTC, tnagorra commented on src/views/RegionAdditionalInfo/i18n.json
> +        "NoDataMessage": "No Data to Display"
```suggestion
        "NoDataMessage": "No data to display"
```

2023-08-22 07:55 UTC, tnagorra approved these changes

2023-08-22 08:30 UTC, frozenhelium requested changes

2023-08-22 08:30 UTC, frozenhelium commented on src/components/List/index.tsx
> +        withMessage = true,
We should use opposite prop and make it by default false

2023-08-22 08:30 UTC, frozenhelium commented on src/components/List/index.tsx
> +        withMessage = true,
We'll later on add a bare list to fix this

2023-08-22 08:30 UTC, frozenhelium commented on src/views/RegionAdditionalInfo/styles.module.css
> +.region-preparedness {
This should match the name of component
```suggestion
.region-additional-info {
```

2023-08-22 08:30 UTC, frozenhelium commented on src/views/RegionAdditionalInfo/styles.module.css
> +            }
We should use grid for the styling here

2023-08-22 08:30 UTC, frozenhelium commented on src/views/RegionAdditionalInfo/index.tsx
> +        <div className={styles.regionPreparedness}>
We should use component name for the main container styling
```suggestion
        <div className={styles.regionAdditionalInfo}>
```

2023-08-22 08:38 UTC, frozenhelium approved these changes

2023-08-22 08:44 UTC, merged