Add threeW Activity detail page
IFRCGo/go-web-app pull request #89
Opened 2023-08-17 11:06 UTC by barshathakuri

## Changes
- Add threeW detail page

## This PR doesn't introduce:
- [x] typos
- [x] conflict markers
- [x] unwanted comments
- [x] temporary files, auto-generated files or secret keys
- [x] `console.log` meant for debugging
- [x] codegen errors

2023-08-18 06:55 UTC, samshara commented on src/App/routes.tsx
> +const emergencyThreeWFormDetails = customWrapRoute({
```suggestion
const threeWActivityDetail = customWrapRoute({
```

2023-08-18 06:55 UTC, samshara commented on src/App/routes.tsx
> +        render: () => import('#views/EmergencyThreeWDetails'),
```suggestion
        render: () => import('#views/ThreeWActivityDetail'),
```

2023-08-18 06:55 UTC, samshara commented on src/views/EmergencyThreeWDetails/index.tsx
> +export const ACTIVITY_LEADER_NS = 'national_society';
add `satisfies`

2023-08-18 06:55 UTC, samshara commented on src/views/EmergencyThreeWDetails/index.tsx
> +        },
```suggestion
        pathVariables: isDefined(activityId) ? {
            id: Number(activityId),
        } : undefined,
```

2023-08-18 06:55 UTC, samshara commented on src/views/EmergencyThreeWDetails/index.tsx
> +            (optionsResponse?.actions?.map((detail) => detail.supplies_details)?.flat(1)),
```suggestion
            (optionsResponse?.actions?.map((detail) => detail.supplies_details)?.flat()),
```

2023-08-18 06:55 UTC, samshara commented on src/views/EmergencyThreeWDetails/index.tsx
> +                                ),
Let's remove span

2023-08-18 06:55 UTC, samshara commented on src/views/EmergencyThreeWDetails/index.tsx
> +                                    </div>
Let's find data from server which has disaggregated data and render it

2023-08-18 06:55 UTC, samshara commented on src/views/EmergencyThreeWDetails/index.tsx
> +                                        ))}
Let's use better name instead of `k`

2023-08-18 06:57 UTC, samshara commented on src/views/EmergencyThreeWDetails/index.tsx
> +                                        ))}
Use Object.entries to iterate over an object type. We don't need to get the values by accessing again.

2023-08-20 04:55 UTC, tnagorra commented on src/views/EmergencyThreeWDetails/index.tsx
> +            (optionsResponse?.actions?.map((detail) => detail.supplies_details)?.flat(1)),
We can also use flatMap directly

2023-08-20 04:57 UTC, tnagorra requested changes

2023-08-20 04:57 UTC, tnagorra commented on src/views/EmergencyThreeWDetails/index.tsx
> +                                            <>
Do we need these fragments?

2023-08-20 04:57 UTC, tnagorra commented on src/views/EmergencyThreeWDetails/index.tsx
> +                                        {/* TODO */}
What is the TODO? Let's add what is remaining

2023-08-20 04:57 UTC, tnagorra commented on src/views/EmergencyThreeWDetails/index.tsx
> +                                        ) as unknown as number[]).map((k) => (
We cannot call Object.keys on undefined

2023-08-23 08:51 UTC, barshathakuri commented on src/views/EmergencyThreeWDetails/index.tsx
> +                                            <>
yes

2023-08-23 13:24 UTC, AdityaKhatri commented on src/views/ThreeWActivityDetail/index.tsx
> +                                                                    label={strings.emergencyMale}
Use list

2023-08-26 14:37 UTC, frozenhelium requested changes
`SimplifiedReportListItem` is unused

2023-08-26 15:06 UTC, frozenhelium requested changes
- Remove all additional / unnecessary styling
- Give components proper names
- Reuse generated types
- DO NOT use prettier auto formatting

2023-08-29 16:16 UTC, tnagorra commented on src/App/routes.tsx
> +});
Is it correct to add this here? We should already have a activity edit page.

2023-08-29 16:16 UTC, tnagorra commented on src/views/ThreeWActivityDetail/index.tsx
> +import { GoApiResponse, useRequest } from '#utils/restRequest';
```suggestion
import { type GoApiResponse, useRequest } from '#utils/restRequest';
```

2023-08-29 16:16 UTC, tnagorra commented on src/views/ThreeWActivityDetail/index.tsx
> +const simplifiedKeySelector = (item: ActivityItem) => item.id;
Let's use function instead of arrow functions as arrow functions are not named.

2023-08-29 16:16 UTC, tnagorra commented on src/views/ThreeWActivityDetail/index.tsx
> +                            {emergencyResponse?.modified_by_details && (
```suggestion
                            {isDefined(emergencyResponse?.modified_by_details) && (
```

2023-08-29 16:16 UTC, tnagorra commented on src/views/ThreeWActivityDetail/ActivityListItem/index.tsx
> +    });
We should not call request on an item that is being rendered on a list.
This will call the same request for each item.

2023-08-29 16:16 UTC, tnagorra commented on src/views/ThreeWActivityDetail/ActivityListItem/index.tsx
> +    ), [optionsResponse?.actions]);
Need to check if this is correct.

2023-08-29 16:16 UTC, tnagorra commented on src/views/ThreeWActivityDetail/ActivityListItem/index.tsx
> +                        ) as unknown as number[]).map((supply) => (
Casting the value of Object.keys as number[] is not correct. This will always be string[]

2023-08-29 16:16 UTC, tnagorra commented on src/views/ThreeWActivityDetail/ActivityListItem/index.tsx
> +            {activitySupply && Object.keys(activitySupply).length > 0 && (
```suggestion
            {isDefined(activitySupply) && Object.keys(activitySupply).length > 0 && (
```

2023-08-29 16:16 UTC, tnagorra commented on src/views/ThreeWActivityDetail/ActivityListItem/index.tsx
> +                    {activitySupply
We don't need to check for activitySuppply again, as it has already been checked.

2023-08-31 17:01 UTC, tnagorra requested changes

2023-08-31 17:01 UTC, tnagorra commented on src/views/ThreeWActivityDetail/ActivityListItem/index.tsx
> +}
Let's directly pass the activity item.

2023-08-31 17:01 UTC, tnagorra commented on src/views/ThreeWActivityDetail/ActivityListItem/index.tsx
> +                    ))}
Let's not use Object.keys or Object.entries to render components

2023-08-31 17:01 UTC, tnagorra commented on src/views/ThreeWActivityDetail/ActivityListItem/index.tsx
> +            {Object.keys(customSupply).length > 0 && (
Let's not use Object.keys or Object.entries to render components

2023-08-31 17:01 UTC, tnagorra commented on src/views/ThreeWActivityDetail/ActivityListItem/index.tsx
> +                            ([supply, value]) => (
Let's not use Object.keys or Object.entries to render components

2023-08-31 17:01 UTC, tnagorra commented on src/views/ThreeWActivityDetail/index.tsx
> +                </Link>
Let's use the updated Link props

2023-09-09 13:14 UTC, tnagorra commented on src/views/AccountThreeWForms/ThreeWTableActions/index.tsx
>  })
Do we need to change these types?

2023-09-11 09:04 UTC, merged