Map component for NS local unit
IFRCGo/go-web-app pull request #910
Opened 2024-05-02 09:48 UTC by shreeyash07

## Addresses:
- #823 
- #858 

## Changes
- Update map details in map component in local unit
- Update map details in map tooltip
- Add local unit icons and healthcare icons
- Add Legends in map

## This PR doesn't introduce:
- [x] typos
- [x] conflict markers
- [x] unwanted comments
- [x] temporary files, auto-generated files or secret keys
- [x] `console.log` meant for debugging
- [x] codegen errors

2024-05-07 12:30 UTC, samshara approved these changes

2024-05-08 03:43 UTC, frozenhelium requested changes
Lets remove all the icons

2024-05-08 03:43 UTC, frozenhelium commented on app/src/utils/constants.ts
Let's not remove the headings

2024-05-08 03:44 UTC, frozenhelium commented on app/src/utils/constants.ts
Also remove unused translations and styling

2024-05-08 03:45 UTC, frozenhelium commented on app/src/views/CountryNsOverviewContextAndStructure/NationalSocietyLocalUnits/common.ts
> +export const TYPE_ADMINISTRATIVE = 1;
Remove unused constants

2024-05-08 03:48 UTC, frozenhelium commented on app/src/views/CountryNsOverviewContextAndStructure/NationalSocietyLocalUnits/LocalUnitsMap/index.tsx
> +        pathVariables: {
Let's not use -1 here

2024-05-08 04:23 UTC, shreeyash07 commented on app/src/views/CountryNsOverviewContextAndStructure/NationalSocietyLocalUnits/common.ts
> +export const TYPE_ADMINISTRATIVE = 1;
no unused constants are present

2024-05-08 04:56 UTC, frozenhelium approved these changes

2024-05-08 05:05 UTC, frozenhelium commented on app/src/views/CountryNsOverviewContextAndStructure/NationalSocietyLocalUnits/common.ts
> +export const TYPE_ADMINISTRATIVE = 1;
These constants are not used anywhere

```
export const TYPE_ADMINISTRATIVE = 1;
export const TYPE_HEALTHCARE = 2;
export const TYPE_EMERGENCY_RESPONSE = 3;
export const TYPE_HUMANITARIAN = 4;
export const TYPE_TRAINING = 5;
export const TYPE_OTHER = 6;

export const TYPE_HEALTH_AMBULANCE = 1;
export const TYPE_HEALTH_BLOOD_CENTER = 2;
export const TYPE_HEALTH_HOSPITAL = 3;
export const TYPE_HEALTH_PHARMACY = 4;
export const TYPE_HEALTH_PHC_CENTER = 5;
export const TYPE_HEALTH_RESIDENTIAL = 6;
export const TYPE_HEALTH_TRAINING = 7;
export const TYPE_HEALTH_SPECIAL_SERVICES = 8;
export const TYPE_HEALTH_OTHERS = 9;
```

2024-05-08 05:47 UTC, frozenhelium approved these changes

2024-05-08 05:53 UTC, merged