Add flash update form
IFRCGo/go-web-app pull request #95
Opened 2023-08-20 11:40 UTC by AdityaKhatri

## This PR doesn't introduce:
- [ ] typos
- [ ] conflict markers
- [ ] unwanted comments
- [ ] temporary files, auto-generated files or secret keys
- [ ] `console.log` meant for debugging
- [ ] codegen errors

2023-08-26 10:12 UTC, tnagorra requested changes

2023-08-26 10:12 UTC, tnagorra commented on src/views/FlashUpdateForm/schema.ts
> +                console.log('here', countryIds);
Let's remove console.log

2023-08-28 05:14 UTC, tnagorra requested changes

2023-08-28 05:14 UTC, tnagorra commented on src/views/FlashUpdateForm/ActionsTab/ActionInput/index.tsx
> +    actionOptions: Action[];
```suggestion
    options: Action[];
```

2023-08-28 05:14 UTC, tnagorra commented on src/views/FlashUpdateForm/ActionsTab/ActionInput/index.tsx
> +        <div className={styles.actionInput}>
Let's add NonFieldError

2023-08-28 05:14 UTC, tnagorra commented on src/views/FlashUpdateForm/ActionsTab/ActionInput/index.tsx
> +                keySelector={(d) => d.id}
Let's not inline functions

2023-08-28 05:14 UTC, tnagorra commented on src/views/FlashUpdateForm/ActionsTab/index.tsx
> +} from '@togglecorp/toggle-form';
```suggestion
import { useMemo } from 'react';
import {
    type EntriesAsList,
    type Error,
    useFormArray,
    getErrorObject,
} from '@togglecorp/toggle-form';
```

2023-08-28 05:14 UTC, tnagorra commented on src/views/FlashUpdateForm/ActionsTab/index.tsx
> +import { type GoApiResponse } from '#utils/restRequest';
Let's keep this in single import

2023-08-28 05:14 UTC, tnagorra commented on src/views/FlashUpdateForm/ActionsTab/index.tsx
> +    }, [actionsResponse?.results]);
We might have similar logic in field update. Let's see if we can re-use this.

2023-08-28 05:14 UTC, tnagorra commented on src/views/FlashUpdateForm/ActionsTab/index.tsx
> +    ] as const), [strings]);
Let's not use array returns

2023-08-28 05:14 UTC, tnagorra commented on src/views/FlashUpdateForm/ActionsTab/index.tsx
> +            {value?.actions_taken?.map((actionTaken, index) => (
Let's add NonFieldErrors here

2023-08-28 05:14 UTC, tnagorra commented on src/views/FlashUpdateForm/ContextTab/CountryProvinceInput/index.tsx
> +    const handleDistrictChange = useCallback((newValue: number[] | undefined) => {
We might not need this function anymore.

2023-08-28 05:14 UTC, tnagorra commented on src/views/FlashUpdateForm/ContextTab/CountryProvinceInput/index.tsx
> +            <CountrySelectInput
Let's add NonFieldErrors

2023-08-28 05:14 UTC, tnagorra commented on src/views/FlashUpdateForm/ContextTab/MultiImageWithCaptionInput/index.tsx
> +    SetValueArg,
```suggestion
import {
    type ArrayError,
    getErrorObject,
    useFormArray,
    type SetValueArg,
```

2023-08-28 05:14 UTC, tnagorra commented on src/views/FlashUpdateForm/ContextTab/MultiImageWithCaptionInput/index.tsx
> +            }
Why are we calling individual setFieldValue and what happens when oldValue is defined?

2023-08-28 05:14 UTC, tnagorra commented on src/views/FlashUpdateForm/ContextTab/MultiImageWithCaptionInput/index.tsx
> +            {value && (
```suggestion
            {value && value.length > 0 && (
```

2023-08-28 05:14 UTC, tnagorra commented on src/views/FlashUpdateForm/ContextTab/MultiImageWithCaptionInput/index.tsx
> +                        }
Why are we checking for `id`? Do we always upload the data and then attach them? In that case, wouldn't we always have id?

2023-08-28 05:14 UTC, tnagorra commented on src/views/FlashUpdateForm/ContextTab/ReferenceInput/index.tsx
> +} from '@togglecorp/toggle-form';
```suggestion
import {
    type ArrayError,
    useFormObject,
    type SetValueArg,
    getErrorObject,
} from '@togglecorp/toggle-form';
```

2023-08-28 05:14 UTC, tnagorra commented on src/views/FlashUpdateForm/ContextTab/ReferenceInput/index.tsx
> +};
```suggestion
const defaultFormValues: PartialReferenceType = () => ({
    client_id: randomString(),
});
```

2023-08-28 05:14 UTC, tnagorra commented on src/views/FlashUpdateForm/ContextTab/ReferenceInput/index.tsx
> +        <div className={styles.reference}>
Let's add NonFieldError

2023-08-28 05:14 UTC, tnagorra commented on src/views/FlashUpdateForm/schema.ts
> +};
Let's use DeepReplace

2023-08-28 05:14 UTC, tnagorra commented on src/views/FlashUpdateForm/schema.ts
> +            ['country_district'] as const,
This condition is very weird.
Also we do not need `const`.

2023-08-28 05:14 UTC, tnagorra commented on src/views/FlashUpdateForm/ContextTab/index.tsx
> +        onValueChange(`${countriesTitles} - ${selectedHazard?.name}  ${date}`, 'title');
```suggestion
        onValueChange(`${countriesTitles || 'Countries'} - ${selectedHazard?.name || 'Hazard'}  ${date}`, 'title');
```

2023-08-28 05:14 UTC, tnagorra commented on src/views/FlashUpdateForm/ContextTab/index.tsx
> +        const date = `${mm}/${yyyy}`;
We might already have a util for this

2023-08-28 05:14 UTC, tnagorra commented on src/views/FlashUpdateForm/ContextTab/index.tsx
> +                {value.references?.map((reference, index) => (
Let's add NonFieldErrors

2023-08-28 05:14 UTC, tnagorra commented on src/views/FlashUpdateForm/FocalPointsTab/index.tsx
> +            <Container>
Let's add NonFieldErrors

2023-08-28 05:14 UTC, tnagorra commented on src/views/FlashUpdateForm/index.tsx
> +}
Let's use the approach used in FieldReportForm

2023-08-28 05:14 UTC, tnagorra commented on src/views/FlashUpdateForm/index.tsx
> +];
Can we check if DREF form also uses similar methodology?

2023-08-28 05:14 UTC, tnagorra commented on src/views/FlashUpdateForm/index.tsx
> +                })),
Let's use the injectClientId helper.
Also, we don't need to use the id

2023-08-28 05:14 UTC, tnagorra commented on src/views/FlashUpdateForm/index.tsx
> +            );
Let's add a NOTE to navigate to details page.

2023-08-28 05:14 UTC, tnagorra commented on src/views/FlashUpdateForm/index.tsx
> +            );
Let's add a NOTE to navigate to details page.

2023-08-28 05:14 UTC, tnagorra commented on src/views/FlashUpdateForm/index.tsx
> +                    )}
We should scroll to top when form is submitted. Let's check Field Report form

2023-08-28 06:04 UTC, AdityaKhatri commented on src/views/FlashUpdateForm/FocalPointsTab/index.tsx
> +            <Container>
Not required

2023-08-28 10:36 UTC, tnagorra approved these changes

2023-08-28 10:37 UTC, merged